//
// Copyright goblinhack@gmail.com
//

#include "my_tile.hpp"
#include "my_ui.hpp"

void gfx_init_12x12(void)
{
  const char *tiles[] = {
      /* clang-format off */
        // ##############################################################################
        "rock1.IS_JOIN_TL2",
        "rock1.IS_JOIN_T_3",
        "rock1.IS_JOIN_TR2",
        "rock1.IS_JOIN_TOP",
        "rock1.IS_JOIN_X4_180",
        "rock1.IS_JOIN_X4_270",
        "rock1.IS_JOIN_X2_270",
        "rock1.IS_JOIN_X2",
        "rock1.IS_JOIN_X1_180",
        "rock1.IS_JOIN_X1",
        "rock1.IS_JOIN_X",
        "",
        "",
        "",
        "",
        "",
        // ##############################################################################
        "rock1.IS_JOIN_T270_3",
        "rock1.IS_JOIN_BLOCK",
        "rock1.IS_JOIN_T90_3",
        "rock1.IS_JOIN_VERT",
        "rock1.IS_JOIN_X4_90",
        "rock1.IS_JOIN_X4",
        "rock1.IS_JOIN_X2_180",
        "rock1.IS_JOIN_X2_90",
        "rock1.IS_JOIN_X1_90",
        "rock1.IS_JOIN_X1_270",
        "rock1.IS_JOIN_X3_180",
        "rock1.IS_JOIN_X3",
        "",
        "",
        "",
        "",
        // ##############################################################################
        "rock1.IS_JOIN_BL2",
        "rock1.IS_JOIN_T180_3",
        "rock1.IS_JOIN_BR2",
        "rock1.IS_JOIN_BOT",
        "rock1.IS_JOIN_T_1",
        "rock1.IS_JOIN_T_2",
        "rock1.IS_JOIN_T270_2",
        "rock1.IS_JOIN_T90_1",
        "rock1.IS_JOIN_T",
        "rock1.IS_JOIN_T90",
        "rock1.IS_JOIN_TL",
        "rock1.IS_JOIN_TR",
        "",
        "",
        "",
        "",
        // ##############################################################################
        "rock1.IS_JOIN_LEFT",
        "rock1.IS_JOIN_HORIZ",
        "rock1.IS_JOIN_RIGHT",
        "rock1.IS_JOIN_NODE",
        "rock1.IS_JOIN_T180_2",
        "rock1.IS_JOIN_T180_1",
        "rock1.IS_JOIN_T270_1",
        "rock1.IS_JOIN_T90_2",
        "rock1.IS_JOIN_T270",
        "rock1.IS_JOIN_T180",
        "rock1.IS_JOIN_BL",
        "rock1.IS_JOIN_BR",
        "",
        "",
        "",
        "",
        // ##############################################################################
        "wall1.IS_JOIN_TL2",
        "wall1.IS_JOIN_T_3",
        "wall1.IS_JOIN_TR2",
        "wall1.IS_JOIN_TOP",
        "wall1.IS_JOIN_X4_180",
        "wall1.IS_JOIN_X4_270",
        "wall1.IS_JOIN_X2_270",
        "wall1.IS_JOIN_X2",
        "wall1.IS_JOIN_X1_180",
        "wall1.IS_JOIN_X1",
        "wall1.IS_JOIN_X",
        "",
        "",
        "",
        "",
        "",
        // ##############################################################################
        "wall1.IS_JOIN_T270_3",
        "wall1.IS_JOIN_BLOCK",
        "wall1.IS_JOIN_T90_3",
        "wall1.IS_JOIN_VERT",
        "wall1.IS_JOIN_X4_90",
        "wall1.IS_JOIN_X4",
        "wall1.IS_JOIN_X2_180",
        "wall1.IS_JOIN_X2_90",
        "wall1.IS_JOIN_X1_90",
        "wall1.IS_JOIN_X1_270",
        "wall1.IS_JOIN_X3_180",
        "wall1.IS_JOIN_X3",
        "",
        "",
        "",
        "",
        // ##############################################################################
        "wall1.IS_JOIN_BL2",
        "wall1.IS_JOIN_T180_3",
        "wall1.IS_JOIN_BR2",
        "wall1.IS_JOIN_BOT",
        "wall1.IS_JOIN_T_1",
        "wall1.IS_JOIN_T_2",
        "wall1.IS_JOIN_T270_2",
        "wall1.IS_JOIN_T90_1",
        "wall1.IS_JOIN_T",
        "wall1.IS_JOIN_T90",
        "wall1.IS_JOIN_TL",
        "wall1.IS_JOIN_TR",
        "",
        "",
        "",
        "",
        // ##############################################################################
        "wall1.IS_JOIN_LEFT",
        "wall1.IS_JOIN_HORIZ",
        "wall1.IS_JOIN_RIGHT",
        "wall1.IS_JOIN_NODE",
        "wall1.IS_JOIN_T180_2",
        "wall1.IS_JOIN_T180_1",
        "wall1.IS_JOIN_T270_1",
        "wall1.IS_JOIN_T90_2",
        "wall1.IS_JOIN_T270",
        "wall1.IS_JOIN_T180",
        "wall1.IS_JOIN_BL",
        "wall1.IS_JOIN_BR",
        "",
        "",
        "",
        "",
        // ##############################################################################
        "floor.1",
        "floor.2",
        "floor.3",
        "floor.4",
        "floor.5",
        "floor.6",
        "floor.7",
        "floor.8",
        "floor.9",
        "floor.10",
        "floor.11",
        "floor.12",
        "floor.13",
        "floor.14",
        "floor.15",
        "floor.16",
        // ##############################################################################
        "dirt.1",
        "dirt.2",
        "dirt.3",
        "dirt.4",
        "dirt.5",
        "dirt.6",
        "dirt.7",
        "dirt.8",
        "dirt.9",
        "dirt.10",
        "dirt.11",
        "dirt.12",
        "dirt.13",
        "dirt.14",
        "dirt.15",
        "dirt.16",
        // ##############################################################################
        "player.idle.0",
        "player.idle.1",
        "cursor_path",
        "cursor_at",
        "exit.0",
        "door.0",
        "key.0",
        "key.1",
        "treasure.0",
        "treasure.1",
        "",
        "",
        "",
        "",
        "",
        "",
        // ##############################################################################
      /* clang-format on */
  };
  tile_load_arr("data/gfx/tiles_12x12.tga", "tiles_12x12", TILE_WIDTH, TILE_HEIGHT, ARRAY_SIZE(tiles), tiles);
}
