//
// Copyright goblinhack@gmail.com
//

#include "my_tile.hpp"
#include "my_ui.hpp"

void gfx_init_24x24_water(void)
{
  const char *tiles[] = {
      /* clang-format off */
        // ##############################################################################
        "water1.IS_JOIN_TL2",
        "water1.IS_JOIN_T_3",
        "water1.IS_JOIN_TR2",
        "water1.IS_JOIN_TOP",
        "water1.IS_JOIN_X4_180",
        "water1.IS_JOIN_X4_270",
        "water1.IS_JOIN_X2_270",
        "water1.IS_JOIN_X2",
        "water1.IS_JOIN_X1_180",
        "water1.IS_JOIN_X1",
        "water1.IS_JOIN_X",
        "",
        "",
        "",
        "",
        "",
        // ##############################################################################
        "water1.IS_JOIN_T270_3",
        "water1.IS_JOIN_BLOCK",
        "water1.IS_JOIN_T90_3",
        "water1.IS_JOIN_VERT",
        "water1.IS_JOIN_X4_90",
        "water1.IS_JOIN_X4",
        "water1.IS_JOIN_X2_180",
        "water1.IS_JOIN_X2_90",
        "water1.IS_JOIN_X1_90",
        "water1.IS_JOIN_X1_270",
        "water1.IS_JOIN_X3_180",
        "water1.IS_JOIN_X3",
        "",
        "",
        "",
        "",
        // ##############################################################################
        "water1.IS_JOIN_BL2",
        "water1.IS_JOIN_T180_3",
        "water1.IS_JOIN_BR2",
        "water1.IS_JOIN_BOT",
        "water1.IS_JOIN_T_1",
        "water1.IS_JOIN_T_2",
        "water1.IS_JOIN_T270_2",
        "water1.IS_JOIN_T90_1",
        "water1.IS_JOIN_T",
        "water1.IS_JOIN_T90",
        "water1.IS_JOIN_TL",
        "water1.IS_JOIN_TR",
        "",
        "",
        "",
        "",
        // ##############################################################################
        "water1.IS_JOIN_LEFT",
        "water1.IS_JOIN_HORIZ",
        "water1.IS_JOIN_RIGHT",
        "water1.IS_JOIN_NODE",
        "water1.IS_JOIN_T180_2",
        "water1.IS_JOIN_T180_1",
        "water1.IS_JOIN_T270_1",
        "water1.IS_JOIN_T90_2",
        "water1.IS_JOIN_T270",
        "water1.IS_JOIN_T180",
        "water1.IS_JOIN_BL",
        "water1.IS_JOIN_BR",
        "",
        "",
        "",
        "",
        // ##############################################################################
        "deep_water1.IS_JOIN_TL2",
        "deep_water1.IS_JOIN_T_3",
        "deep_water1.IS_JOIN_TR2",
        "deep_water1.IS_JOIN_TOP",
        "deep_water1.IS_JOIN_X4_180",
        "deep_water1.IS_JOIN_X4_270",
        "deep_water1.IS_JOIN_X2_270",
        "deep_water1.IS_JOIN_X2",
        "deep_water1.IS_JOIN_X1_180",
        "deep_water1.IS_JOIN_X1",
        "deep_water1.IS_JOIN_X",
        "",
        "",
        "",
        "",
        "",
        // ##############################################################################
        "deep_water1.IS_JOIN_T270_3",
        "deep_water1.IS_JOIN_BLOCK",
        "deep_water1.IS_JOIN_T90_3",
        "deep_water1.IS_JOIN_VERT",
        "deep_water1.IS_JOIN_X4_90",
        "deep_water1.IS_JOIN_X4",
        "deep_water1.IS_JOIN_X2_180",
        "deep_water1.IS_JOIN_X2_90",
        "deep_water1.IS_JOIN_X1_90",
        "deep_water1.IS_JOIN_X1_270",
        "deep_water1.IS_JOIN_X3_180",
        "deep_water1.IS_JOIN_X3",
        "",
        "",
        "",
        "",
        // ##############################################################################
        "deep_water1.IS_JOIN_BL2",
        "deep_water1.IS_JOIN_T180_3",
        "deep_water1.IS_JOIN_BR2",
        "deep_water1.IS_JOIN_BOT",
        "deep_water1.IS_JOIN_T_1",
        "deep_water1.IS_JOIN_T_2",
        "deep_water1.IS_JOIN_T270_2",
        "deep_water1.IS_JOIN_T90_1",
        "deep_water1.IS_JOIN_T",
        "deep_water1.IS_JOIN_T90",
        "deep_water1.IS_JOIN_TL",
        "deep_water1.IS_JOIN_TR",
        "",
        "",
        "",
        "",
        // ##############################################################################
        "deep_water1.IS_JOIN_LEFT",
        "deep_water1.IS_JOIN_HORIZ",
        "deep_water1.IS_JOIN_RIGHT",
        "deep_water1.IS_JOIN_NODE",
        "deep_water1.IS_JOIN_T180_2",
        "deep_water1.IS_JOIN_T180_1",
        "deep_water1.IS_JOIN_T270_1",
        "deep_water1.IS_JOIN_T90_2",
        "deep_water1.IS_JOIN_T270",
        "deep_water1.IS_JOIN_T180",
        "deep_water1.IS_JOIN_BL",
        "deep_water1.IS_JOIN_BR",
        "",
        "",
        "",
        "",
        // ##############################################################################
      /* clang-format on */
  };
  tile_load_arr("data/gfx/tiles_24x24_water.tga", "tiles_24x24_water", TILE_WIDTH, TILE_HEIGHT, ARRAY_SIZE(tiles),
                tiles);
}
