//
// Copyright goblinhack@gmail.com
//

#include "my_tile.hpp"
#include "my_ui.hpp"

void gfx_init_24x24_water(void)
{
  const char *water_tiles[] = {
      /* clang-format off */
        // ##############################################################################
        "water1.IS_JOIN_TL2.0",
        "water1.IS_JOIN_T_3.0",
        "water1.IS_JOIN_TR2.0",
        "water1.IS_JOIN_TOP.0",
        "water1.IS_JOIN_X4_180.0",
        "water1.IS_JOIN_X4_270.0",
        "water1.IS_JOIN_X2_270.0",
        "water1.IS_JOIN_X2.0",
        "water1.IS_JOIN_X1_180.0",
        "water1.IS_JOIN_X1.0",
        "water1.IS_JOIN_X.0",
        "",
        // ##############################################################################
        "water1.IS_JOIN_T270_3.0",
        "water1.IS_JOIN_BLOCK.0",
        "water1.IS_JOIN_T90_3.0",
        "water1.IS_JOIN_VERT.0",
        "water1.IS_JOIN_X4_90.0",
        "water1.IS_JOIN_X4.0",
        "water1.IS_JOIN_X2_180.0",
        "water1.IS_JOIN_X2_90.0",
        "water1.IS_JOIN_X1_90.0",
        "water1.IS_JOIN_X1_270.0",
        "water1.IS_JOIN_X3_180.0",
        "water1.IS_JOIN_X3.0",
        // ##############################################################################
        "water1.IS_JOIN_BL2.0",
        "water1.IS_JOIN_T180_3.0",
        "water1.IS_JOIN_BR2.0",
        "water1.IS_JOIN_BOT.0",
        "water1.IS_JOIN_T_1.0",
        "water1.IS_JOIN_T_2.0",
        "water1.IS_JOIN_T270_2.0",
        "water1.IS_JOIN_T90_1.0",
        "water1.IS_JOIN_T.0",
        "water1.IS_JOIN_T90.0",
        "water1.IS_JOIN_TL.0",
        "water1.IS_JOIN_TR.0",
        // ##############################################################################
        "water1.IS_JOIN_LEFT.0",
        "water1.IS_JOIN_HORIZ.0",
        "water1.IS_JOIN_RIGHT.0",
        "water1.IS_JOIN_NODE.0",
        "water1.IS_JOIN_T180_2.0",
        "water1.IS_JOIN_T180_1.0",
        "water1.IS_JOIN_T270_1.0",
        "water1.IS_JOIN_T90_2.0",
        "water1.IS_JOIN_T270.0",
        "water1.IS_JOIN_T180.0",
        "water1.IS_JOIN_BL.0",
        "water1.IS_JOIN_BR.0",
        // ##############################################################################
        "water1.IS_JOIN_TL2.1",
        "water1.IS_JOIN_T_3.1",
        "water1.IS_JOIN_TR2.1",
        "water1.IS_JOIN_TOP.1",
        "water1.IS_JOIN_X4_180.1",
        "water1.IS_JOIN_X4_270.1",
        "water1.IS_JOIN_X2_270.1",
        "water1.IS_JOIN_X2.1",
        "water1.IS_JOIN_X1_180.1",
        "water1.IS_JOIN_X1.1",
        "water1.IS_JOIN_X.1",
        "",
        // ##############################################################################
        "water1.IS_JOIN_T270_3.1",
        "water1.IS_JOIN_BLOCK.1",
        "water1.IS_JOIN_T90_3.1",
        "water1.IS_JOIN_VERT.1",
        "water1.IS_JOIN_X4_90.1",
        "water1.IS_JOIN_X4.1",
        "water1.IS_JOIN_X2_180.1",
        "water1.IS_JOIN_X2_90.1",
        "water1.IS_JOIN_X1_90.1",
        "water1.IS_JOIN_X1_270.1",
        "water1.IS_JOIN_X3_180.1",
        "water1.IS_JOIN_X3.1",
        // ##############################################################################
        "water1.IS_JOIN_BL2.1",
        "water1.IS_JOIN_T180_3.1",
        "water1.IS_JOIN_BR2.1",
        "water1.IS_JOIN_BOT.1",
        "water1.IS_JOIN_T_1.1",
        "water1.IS_JOIN_T_2.1",
        "water1.IS_JOIN_T270_2.1",
        "water1.IS_JOIN_T90_1.1",
        "water1.IS_JOIN_T.1",
        "water1.IS_JOIN_T90.1",
        "water1.IS_JOIN_TL.1",
        "water1.IS_JOIN_TR.1",
        // ##############################################################################
        "water1.IS_JOIN_LEFT.1",
        "water1.IS_JOIN_HORIZ.1",
        "water1.IS_JOIN_RIGHT.1",
        "water1.IS_JOIN_NODE.1",
        "water1.IS_JOIN_T180_2.1",
        "water1.IS_JOIN_T180_1.1",
        "water1.IS_JOIN_T270_1.1",
        "water1.IS_JOIN_T90_2.1",
        "water1.IS_JOIN_T270.1",
        "water1.IS_JOIN_T180.1",
        "water1.IS_JOIN_BL.1",
        "water1.IS_JOIN_BR.1",
        // ##############################################################################
        "water1.IS_JOIN_TL2.2",
        "water1.IS_JOIN_T_3.2",
        "water1.IS_JOIN_TR2.2",
        "water1.IS_JOIN_TOP.2",
        "water1.IS_JOIN_X4_180.2",
        "water1.IS_JOIN_X4_270.2",
        "water1.IS_JOIN_X2_270.2",
        "water1.IS_JOIN_X2.2",
        "water1.IS_JOIN_X1_180.2",
        "water1.IS_JOIN_X1.2",
        "water1.IS_JOIN_X.2",
        "",
        // ##############################################################################
        "water1.IS_JOIN_T270_3.2",
        "water1.IS_JOIN_BLOCK.2",
        "water1.IS_JOIN_T90_3.2",
        "water1.IS_JOIN_VERT.2",
        "water1.IS_JOIN_X4_90.2",
        "water1.IS_JOIN_X4.2",
        "water1.IS_JOIN_X2_180.2",
        "water1.IS_JOIN_X2_90.2",
        "water1.IS_JOIN_X1_90.2",
        "water1.IS_JOIN_X1_270.2",
        "water1.IS_JOIN_X3_180.2",
        "water1.IS_JOIN_X3.2",
        // ##############################################################################
        "water1.IS_JOIN_BL2.2",
        "water1.IS_JOIN_T180_3.2",
        "water1.IS_JOIN_BR2.2",
        "water1.IS_JOIN_BOT.2",
        "water1.IS_JOIN_T_1.2",
        "water1.IS_JOIN_T_2.2",
        "water1.IS_JOIN_T270_2.2",
        "water1.IS_JOIN_T90_1.2",
        "water1.IS_JOIN_T.2",
        "water1.IS_JOIN_T90.2",
        "water1.IS_JOIN_TL.2",
        "water1.IS_JOIN_TR.2",
        // ##############################################################################
        "water1.IS_JOIN_LEFT.2",
        "water1.IS_JOIN_HORIZ.2",
        "water1.IS_JOIN_RIGHT.2",
        "water1.IS_JOIN_NODE.2",
        "water1.IS_JOIN_T180_2.2",
        "water1.IS_JOIN_T180_1.2",
        "water1.IS_JOIN_T270_1.2",
        "water1.IS_JOIN_T90_2.2",
        "water1.IS_JOIN_T270.2",
        "water1.IS_JOIN_T180.2",
        "water1.IS_JOIN_BL.2",
        "water1.IS_JOIN_BR.2",
        // ##############################################################################
        "water1.IS_JOIN_TL2.3",
        "water1.IS_JOIN_T_3.3",
        "water1.IS_JOIN_TR2.3",
        "water1.IS_JOIN_TOP.3",
        "water1.IS_JOIN_X4_180.3",
        "water1.IS_JOIN_X4_270.3",
        "water1.IS_JOIN_X2_270.3",
        "water1.IS_JOIN_X2.3",
        "water1.IS_JOIN_X1_180.3",
        "water1.IS_JOIN_X1.3",
        "water1.IS_JOIN_X.3",
        "",
        // ##############################################################################
        "water1.IS_JOIN_T270_3.3",
        "water1.IS_JOIN_BLOCK.3",
        "water1.IS_JOIN_T90_3.3",
        "water1.IS_JOIN_VERT.3",
        "water1.IS_JOIN_X4_90.3",
        "water1.IS_JOIN_X4.3",
        "water1.IS_JOIN_X2_180.3",
        "water1.IS_JOIN_X2_90.3",
        "water1.IS_JOIN_X1_90.3",
        "water1.IS_JOIN_X1_270.3",
        "water1.IS_JOIN_X3_180.3",
        "water1.IS_JOIN_X3.3",
        // ##############################################################################
        "water1.IS_JOIN_BL2.3",
        "water1.IS_JOIN_T180_3.3",
        "water1.IS_JOIN_BR2.3",
        "water1.IS_JOIN_BOT.3",
        "water1.IS_JOIN_T_1.3",
        "water1.IS_JOIN_T_2.3",
        "water1.IS_JOIN_T270_2.3",
        "water1.IS_JOIN_T90_1.3",
        "water1.IS_JOIN_T.3",
        "water1.IS_JOIN_T90.3",
        "water1.IS_JOIN_TL.3",
        "water1.IS_JOIN_TR.3",
        // ##############################################################################
        "water1.IS_JOIN_LEFT.3",
        "water1.IS_JOIN_HORIZ.3",
        "water1.IS_JOIN_RIGHT.3",
        "water1.IS_JOIN_NODE.3",
        "water1.IS_JOIN_T180_2.3",
        "water1.IS_JOIN_T180_1.3",
        "water1.IS_JOIN_T270_1.3",
        "water1.IS_JOIN_T90_2.3",
        "water1.IS_JOIN_T270.3",
        "water1.IS_JOIN_T180.3",
        "water1.IS_JOIN_BL.3",
        "water1.IS_JOIN_BR.3",
        // ##############################################################################
      /* clang-format on */
  };
  tile_load_arr("data/gfx/tiles_24x24_water.tga", "tiles_24x24_water", TILE_WIDTH, TILE_HEIGHT,
                ARRAY_SIZE(water_tiles), water_tiles);

  const char *deep_water_tiles[] = {
      /* clang-format off */
        // ##############################################################################
        "deep_water1.IS_JOIN_TL2.0",
        "deep_water1.IS_JOIN_T_3.0",
        "deep_water1.IS_JOIN_TR2.0",
        "deep_water1.IS_JOIN_TOP.0",
        "deep_water1.IS_JOIN_X4_180.0",
        "deep_water1.IS_JOIN_X4_270.0",
        "deep_water1.IS_JOIN_X2_270.0",
        "deep_water1.IS_JOIN_X2.0",
        "deep_water1.IS_JOIN_X1_180.0",
        "deep_water1.IS_JOIN_X1.0",
        "deep_water1.IS_JOIN_X.0",
        "",
        // ##############################################################################
        "deep_water1.IS_JOIN_T270_3.0",
        "deep_water1.IS_JOIN_BLOCK.0",
        "deep_water1.IS_JOIN_T90_3.0",
        "deep_water1.IS_JOIN_VERT.0",
        "deep_water1.IS_JOIN_X4_90.0",
        "deep_water1.IS_JOIN_X4.0",
        "deep_water1.IS_JOIN_X2_180.0",
        "deep_water1.IS_JOIN_X2_90.0",
        "deep_water1.IS_JOIN_X1_90.0",
        "deep_water1.IS_JOIN_X1_270.0",
        "deep_water1.IS_JOIN_X3_180.0",
        "deep_water1.IS_JOIN_X3.0",
        // ##############################################################################
        "deep_water1.IS_JOIN_BL2.0",
        "deep_water1.IS_JOIN_T180_3.0",
        "deep_water1.IS_JOIN_BR2.0",
        "deep_water1.IS_JOIN_BOT.0",
        "deep_water1.IS_JOIN_T_1.0",
        "deep_water1.IS_JOIN_T_2.0",
        "deep_water1.IS_JOIN_T270_2.0",
        "deep_water1.IS_JOIN_T90_1.0",
        "deep_water1.IS_JOIN_T.0",
        "deep_water1.IS_JOIN_T90.0",
        "deep_water1.IS_JOIN_TL.0",
        "deep_water1.IS_JOIN_TR.0",
        // ##############################################################################
        "deep_water1.IS_JOIN_LEFT.0",
        "deep_water1.IS_JOIN_HORIZ.0",
        "deep_water1.IS_JOIN_RIGHT.0",
        "deep_water1.IS_JOIN_NODE.0",
        "deep_water1.IS_JOIN_T180_2.0",
        "deep_water1.IS_JOIN_T180_1.0",
        "deep_water1.IS_JOIN_T270_1.0",
        "deep_water1.IS_JOIN_T90_2.0",
        "deep_water1.IS_JOIN_T270.0",
        "deep_water1.IS_JOIN_T180.0",
        "deep_water1.IS_JOIN_BL.0",
        "deep_water1.IS_JOIN_BR.0",
        // ##############################################################################
        "deep_water1.IS_JOIN_TL2.1",
        "deep_water1.IS_JOIN_T_3.1",
        "deep_water1.IS_JOIN_TR2.1",
        "deep_water1.IS_JOIN_TOP.1",
        "deep_water1.IS_JOIN_X4_180.1",
        "deep_water1.IS_JOIN_X4_270.1",
        "deep_water1.IS_JOIN_X2_270.1",
        "deep_water1.IS_JOIN_X2.1",
        "deep_water1.IS_JOIN_X1_180.1",
        "deep_water1.IS_JOIN_X1.1",
        "deep_water1.IS_JOIN_X.1",
        "",
        // ##############################################################################
        "deep_water1.IS_JOIN_T270_3.1",
        "deep_water1.IS_JOIN_BLOCK.1",
        "deep_water1.IS_JOIN_T90_3.1",
        "deep_water1.IS_JOIN_VERT.1",
        "deep_water1.IS_JOIN_X4_90.1",
        "deep_water1.IS_JOIN_X4.1",
        "deep_water1.IS_JOIN_X2_180.1",
        "deep_water1.IS_JOIN_X2_90.1",
        "deep_water1.IS_JOIN_X1_90.1",
        "deep_water1.IS_JOIN_X1_270.1",
        "deep_water1.IS_JOIN_X3_180.1",
        "deep_water1.IS_JOIN_X3.1",
        // ##############################################################################
        "deep_water1.IS_JOIN_BL2.1",
        "deep_water1.IS_JOIN_T180_3.1",
        "deep_water1.IS_JOIN_BR2.1",
        "deep_water1.IS_JOIN_BOT.1",
        "deep_water1.IS_JOIN_T_1.1",
        "deep_water1.IS_JOIN_T_2.1",
        "deep_water1.IS_JOIN_T270_2.1",
        "deep_water1.IS_JOIN_T90_1.1",
        "deep_water1.IS_JOIN_T.1",
        "deep_water1.IS_JOIN_T90.1",
        "deep_water1.IS_JOIN_TL.1",
        "deep_water1.IS_JOIN_TR.1",
        // ##############################################################################
        "deep_water1.IS_JOIN_LEFT.1",
        "deep_water1.IS_JOIN_HORIZ.1",
        "deep_water1.IS_JOIN_RIGHT.1",
        "deep_water1.IS_JOIN_NODE.1",
        "deep_water1.IS_JOIN_T180_2.1",
        "deep_water1.IS_JOIN_T180_1.1",
        "deep_water1.IS_JOIN_T270_1.1",
        "deep_water1.IS_JOIN_T90_2.1",
        "deep_water1.IS_JOIN_T270.1",
        "deep_water1.IS_JOIN_T180.1",
        "deep_water1.IS_JOIN_BL.1",
        "deep_water1.IS_JOIN_BR.1",
        // ##############################################################################
      /* clang-format on */
  };
  tile_load_arr("data/gfx/tiles_24x24_deep_water.tga", "tiles_24x24_deep_water", TILE_WIDTH, TILE_HEIGHT,
                ARRAY_SIZE(deep_water_tiles), deep_water_tiles);
}
