//
// Copyright goblinhack@gmail.com
//

#include "my_callstack.hpp"
#include "my_level.hpp"
#include "my_level_ext.hpp"

Overrides no_overrides;

//
// Create all test levels
//
void levels_test(Gamep g)
{
  TRACE();

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "simple", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.@..R..xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "treasure", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx...$$$.xx",
                  /* line */ (const char *) "xx.@.$$$.xx",
                  /* line */ (const char *) "xx...$$$.xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* end */ nullptr);

  {
    Overrides overrides;

    overrides[ 'm' ] = [](char c, spoint p) -> Tpp { return tp_find_mand("kobalos"); };
    overrides[ 'n' ] = [](char c, spoint p) -> Tpp { return tp_find_mand("ghost"); };

    level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "monst.1", __FUNCTION__, __LINE__, overrides, 0,
                    /* line */ (const char *) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x...xxxxxxxxx..................................x",
                    /* line */ (const char *) "x...x..........................................x",
                    /* line */ (const char *) "x...x..........................................x",
                    /* line */ (const char *) "x...x..........................................x",
                    /* line */ (const char *) "x...x..........................................x",
                    /* line */ (const char *) "x...x..........................................x",
                    /* line */ (const char *) "x.......@......................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmx",
                    /* line */ (const char *) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    /* end */ nullptr);

    level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "monst", __FUNCTION__, __LINE__, overrides, 0,
                    /* line */ (const char *) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x...xxxxxxxxx..................................x",
                    /* line */ (const char *) "x...x..........................................x",
                    /* line */ (const char *) "x...x..........................................x",
                    /* line */ (const char *) "x...x..........................................x",
                    /* line */ (const char *) "x...x..........................................x",
                    /* line */ (const char *) "x...x..........................................x",
                    /* line */ (const char *) "x.......E......................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "x..............................................x",
                    /* line */ (const char *) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    /* end */ nullptr);
  }

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "lava", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx...L...xx",
                  /* line */ (const char *) "xx...L...xx",
                  /* line */ (const char *) "xx.@.L...xx",
                  /* line */ (const char *) "xx...L...xx",
                  /* line */ (const char *) "xx...L...xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "rock", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx...R...xx",
                  /* line */ (const char *) "xx...R...xx",
                  /* line */ (const char *) "xx.@.R...xx",
                  /* line */ (const char *) "xx...R...xx",
                  /* line */ (const char *) "xx...R...xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "border", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx...X...xx",
                  /* line */ (const char *) "xx...X...xx",
                  /* line */ (const char *) "xx.@.X...xx",
                  /* line */ (const char *) "xx...X...xx",
                  /* line */ (const char *) "xx...X...xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "chasm.1", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx...CCC.xx",
                  /* line */ (const char *) "xx..BCCC.xx",
                  /* line */ (const char *) "xx@.GCCC.xx",
                  /* line */ (const char *) "xx..bCCC.xx",
                  /* line */ (const char *) "xx..gCCC.xx",
                  /* line */ (const char *) "xx...CCC.xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "chasm.9", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "xxxxxxxxxxx", // next level down
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.E.....xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "chasm", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "xxxxxxxxxxx", // all other chasm levels
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx.E.....xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "fire", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xx...!!!.xx",
                  /* line */ (const char *) "xx...b!b.xx",
                  /* line */ (const char *) "xx.@.!b!.xx",
                  /* line */ (const char *) "xx...b!b.xx",
                  /* line */ (const char *) "xx.E.!!!.xx",
                  /* line */ (const char *) "xx.......xx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* line */ (const char *) "xxxxxxxxxxx",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "firemaze", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "           ",
                  /* line */ (const char *) "           ",
                  /* line */ (const char *) "  xxxxxxx  ",
                  /* line */ (const char *) "  xxxbbbx  ",
                  /* line */ (const char *) "  xxxbxbx  ",
                  /* line */ (const char *) "  x@!bxbx  ",
                  /* line */ (const char *) "  xxxxxbx  ",
                  /* line */ (const char *) "  xbbbbbx  ",
                  /* line */ (const char *) "  xxxxxxx  ",
                  /* line */ (const char *) "           ",
                  /* line */ (const char *) "           ",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "bridge1", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "           ",
                  /* line */ (const char *) " xxxxxxxxx ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " x..CCC..x ",
                  /* line */ (const char *) " x.@====.x ",
                  /* line */ (const char *) " x..CCC..x ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " xxxxxxxxx ",
                  /* line */ (const char *) "           ",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "bridge2", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "           ",
                  /* line */ (const char *) " xxxxxxxxx ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " x..LLL..x ",
                  /* line */ (const char *) " x.@====.x ",
                  /* line */ (const char *) " x..LLL..x ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " xxxxxxxxx ",
                  /* line */ (const char *) "           ",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "shove", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "           ",
                  /* line */ (const char *) " xxxxxxxxx ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " x....C..x ",
                  /* line */ (const char *) " x..@BC..x ",
                  /* line */ (const char *) " x....C..x ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " xxxxxxxxx ",
                  /* line */ (const char *) "           ",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "shove.9", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "           ",
                  /* line */ (const char *) " xxxxxxxxx ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " x..E....x ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " xxxxxxxxx ",
                  /* line */ (const char *) "           ",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "barrel", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "           ",
                  /* line */ (const char *) " xxxxxxxxx ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " xbbbbbb.x ",
                  /* line */ (const char *) " xb....b.x ",
                  /* line */ (const char *) " xb.@..b.x ",
                  /* line */ (const char *) " xb....b.x ",
                  /* line */ (const char *) " xbbbbbb.x ",
                  /* line */ (const char *) " x.......x ",
                  /* line */ (const char *) " xxxxxxxxx ",
                  /* line */ (const char *) "           ",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "door_secret", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "           ",
                  /* line */ (const char *) " xxxxx     ",
                  /* line */ (const char *) " x...x     ",
                  /* line */ (const char *) " x...xxxxx ",
                  /* line */ (const char *) " x...x...x ",
                  /* line */ (const char *) " x..@s...x ",
                  /* line */ (const char *) " x...x...x ",
                  /* line */ (const char *) " x...xxxxx ",
                  /* line */ (const char *) " x...x     ",
                  /* line */ (const char *) " xxxxx     ",
                  /* line */ (const char *) "           ",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "door_unlocked", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "           ",
                  /* line */ (const char *) " xxxxx     ",
                  /* line */ (const char *) " x...x     ",
                  /* line */ (const char *) " x...xxxxx ",
                  /* line */ (const char *) " x...x...x ",
                  /* line */ (const char *) " x@..D...x ",
                  /* line */ (const char *) " x...x...x ",
                  /* line */ (const char *) " xk..+...x ",
                  /* line */ (const char *) " x...x...x ",
                  /* line */ (const char *) " x...xxxxx ",
                  /* line */ (const char *) " x...x     ",
                  /* line */ (const char *) " xxxxx     ",
                  /* line */ (const char *) "           ",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "door_locked", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "           ",
                  /* line */ (const char *) " xxxxx     ",
                  /* line */ (const char *) " x...x     ",
                  /* line */ (const char *) " x...xxxxx ",
                  /* line */ (const char *) " x...x...x ",
                  /* line */ (const char *) " x@.k+...x ",
                  /* line */ (const char *) " x...x...x ",
                  /* line */ (const char *) " x...xxxxx ",
                  /* line */ (const char *) " x...x     ",
                  /* line */ (const char *) " xxxxx     ",
                  /* line */ (const char *) "           ",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "item", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "           ",
                  /* line */ (const char *) " xxxxxxxxx ",
                  /* line */ (const char *) " x...$$$$x ",
                  /* line */ (const char *) " x...$$$$x ",
                  /* line */ (const char *) " x...$$$$x ",
                  /* line */ (const char *) " x..@$$$$x ",
                  /* line */ (const char *) " x...$$$$x ",
                  /* line */ (const char *) " x...$$$$x ",
                  /* line */ (const char *) " x...$$$$x ",
                  /* line */ (const char *) " xxxxxxxxx ",
                  /* line */ (const char *) "           ",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "teleport", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "                   ",
                  /* line */ (const char *) "xxxxxx             ",
                  /* line */ (const char *) "x....x             ",
                  /* line */ (const char *) "x....xxxxxxxxxxxxxx",
                  /* line */ (const char *) "x.................x",
                  /* line */ (const char *) "x...bT..@.........x",
                  /* line */ (const char *) "x.................x",
                  /* line */ (const char *) "x....T............x",
                  /* line */ (const char *) "x.................x",
                  /* line */ (const char *) "xxxxxxxxxxxxxxxxxxx",
                  /* line */ (const char *) "                   ",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "teleport-large", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "xxxxxxCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCxxxxxxxx",
                  /* line */ (const char *) "x....xCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCx......x",
                  /* line */ (const char *) "x....xCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCx..T...x",
                  /* line */ (const char *) "x...TxCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCx......x",
                  /* line */ (const char *) "xxxx.xCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCxxxxxxxx",
                  /* line */ (const char *) "CCCC.CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCC.CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCC.CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCxxxxxCCCCC",
                  /* line */ (const char *) "CCCC.CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCx...xCCCCC",
                  /* line */ (const char *) "CCCC....................................T.xCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCx...xCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCxxxxxCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCxxxxxxxxxCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCx.......xCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCx.@..T..xCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCx.......xCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCx.......xCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCxxxxxxxxxCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "xxxxxCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "x...xCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "x.T.xCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "x...xCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "xxxxxCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCxxxxx",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCx...x",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCx.T.x",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCx...x",
                  /* line */ (const char *) "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCxxxxx",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "empty", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x...xxxxxxxxx..................................x",
                  /* line */ (const char *) "x...x..........................................x",
                  /* line */ (const char *) "x...x...@......................................x",
                  /* line */ (const char *) "x...x..........................................x",
                  /* line */ (const char *) "x...x..........................................x",
                  /* line */ (const char *) "x...x..........................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                  /* end */ nullptr);

  level_fixed_add(g, CHANCE_NORMAL, LEVEL_TYPE_TEST, "water", __FUNCTION__, __LINE__, no_overrides, 0,
                  /* line */ (const char *) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x.............B................................x",
                  /* line */ (const char *) "x......xxxx....................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x...........G.......B..........................x",
                  /* line */ (const char *) "x...........G..................................x",
                  /* line */ (const char *) "x.x.........G..................................x",
                  /* line */ (const char *) "x.x...@.....G..................................x",
                  /* line */ (const char *) "x.x............``~~~~~~~~~~~~~~~~~~~~~~~~......x",
                  /* line */ (const char *) "x...........~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.~.~.x",
                  /* line */ (const char *) "x....xxx.`~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.x",
                  /* line */ (const char *) "x........`~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.x",
                  /* line */ (const char *) "x.......``~~~~..~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.x",
                  /* line */ (const char *) "x......```~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~x",
                  /* line */ (const char *) "x......``~~~~~~~~~~~~~..~~~~~~~~~~~~~~~~~~~~~..x",
                  /* line */ (const char *) "x.......`~~~~~~~~~~~~....~~~~~~~~~~~~~~~~~~~~..x",
                  /* line */ (const char *) "x.......~~~~~~~~~~~~~~..~~~~~~~~~~~~~~~~~~~~~..x",
                  /* line */ (const char *) "x......~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...x",
                  /* line */ (const char *) "x.......~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...x",
                  /* line */ (const char *) "x........~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.x",
                  /* line */ (const char *) "x.......~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~..x",
                  /* line */ (const char *) "x........~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.x",
                  /* line */ (const char *) "x.......~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~..x",
                  /* line */ (const char *) "x.......~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~...x",
                  /* line */ (const char *) "x.........~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.......x",
                  /* line */ (const char *) "x...............~~~~~~~~~~~~~~~~~~~............x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "x..............................................x",
                  /* line */ (const char *) "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                  /* end */ nullptr);
}
