//
// Copyright goblinhack@gmail.com
//

#include "my_callstack.hpp"
#include "my_level.hpp"
#include "my_types.hpp"

//
// Create all exit rooms
//
void rooms_prefab_exit(Gamep g)
{
  TRACE();

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " vvv.vvvvvv ",
           /* line */ (const char *) " v........v ",
           /* line */ (const char *) " v.M.......^",
           /* line */ (const char *) " v........v ",
           /* line */ (const char *) " v....v+vvv ",
           /* line */ (const char *) " v....v...v ",
           /* line */ (const char *) "^.....vv..v ",
           /* line */ (const char *) " v.....vE$v ",
           /* line */ (const char *) " vvvvv.vvvv ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvvvv",
           /* line */ (const char *) " v$.v......v",
           /* line */ (const char *) " v..v.E..M.v",
           /* line */ (const char *) " v..s......v",
           /* line */ (const char *) " vvvvBsBvvvv",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    v.M.v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "    vB.Bv   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vv.vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvvvv",
           /* line */ (const char *) " v$.v......v",
           /* line */ (const char *) " v..v.E..M.v",
           /* line */ (const char *) " v..s......v",
           /* line */ (const char *) " vvvvCCCvvvv",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vv.vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvvvv",
           /* line */ (const char *) " v.........v",
           /* line */ (const char *) " v....E..M.v",
           /* line */ (const char *) " v.........v",
           /* line */ (const char *) " vvvvCCCvvvv",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vv.vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvvvv",
           /* line */ (const char *) " v.........v",
           /* line */ (const char *) " v...BEB.M.v",
           /* line */ (const char *) " v.........v",
           /* line */ (const char *) " vvvvCCCvvvv",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vC.Bv   ",
           /* line */ (const char *) "    vB.Cv   ",
           /* line */ (const char *) "    vC.Bv   ",
           /* line */ (const char *) "    vB.Cv   ",
           /* line */ (const char *) "    vC.Bv   ",
           /* line */ (const char *) "    vB.Cv   ",
           /* line */ (const char *) "    vv.vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvvvv",
           /* line */ (const char *) " v.........v",
           /* line */ (const char *) " v...BEB.M.v",
           /* line */ (const char *) " v.........v",
           /* line */ (const char *) " vvv.....vvv",
           /* line */ (const char *) "   v.....v  ",
           /* line */ (const char *) "   vv...vv  ",
           /* line */ (const char *) "    vCCCv   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vCCCv   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vv.vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvvvv",
           /* line */ (const char *) " v$.v......v",
           /* line */ (const char *) " v..v.E..M.v",
           /* line */ (const char *) " v..s......v",
           /* line */ (const char *) " vvvvCCCvvvv",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vv.vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " vvv.vvvvvv ",
           /* line */ (const char *) " v........v ",
           /* line */ (const char *) " v..G......^",
           /* line */ (const char *) " v........v ",
           /* line */ (const char *) " v....CCCCv ",
           /* line */ (const char *) " v....C...v ",
           /* line */ (const char *) "^..M..C.E.v ",
           /* line */ (const char *) " v....C..$v ",
           /* line */ (const char *) " vvvvvvvvvv ",
           /* line */ (const char *) "            ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " vvv.vvvvvv ",
           /* line */ (const char *) " v........v ",
           /* line */ (const char *) " v.M.......^",
           /* line */ (const char *) " v........v ",
           /* line */ (const char *) " v.....```v ",
           /* line */ (const char *) " v....``..v ",
           /* line */ (const char *) "^...```.E.v ",
           /* line */ (const char *) " v.``....$v ",
           /* line */ (const char *) " vvvvvvvvvv ",
           /* line */ (const char *) "            ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^       ",
           /* line */ (const char *) " vvvv.vvvvvv ",
           /* line */ (const char *) " v.........v ",
           /* line */ (const char *) " v.M...B.B.v ",
           /* line */ (const char *) "^.......E...^",
           /* line */ (const char *) " v``...B.B.v ",
           /* line */ (const char *) " v```......v ",
           /* line */ (const char *) " v..``.....v ",
           /* line */ (const char *) " v$g.```...v ",
           /* line */ (const char *) " vvvvvvvvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^     ",
           /* line */ (const char *) " vvvvvvv.vvvv ",
           /* line */ (const char *) " v..........v ",
           /* line */ (const char *) " v..........v ",
           /* line */ (const char *) "^............^",
           /* line */ (const char *) " vvv......vvv ",
           /* line */ (const char *) "   v......v   ",
           /* line */ (const char *) " vvvCCCCCCvvv ",
           /* line */ (const char *) " v...B..B...v ",
           /* line */ (const char *) " v..........v ",
           /* line */ (const char *) " v.E......M.v ",
           /* line */ (const char *) " v...vvvv...v ",
           /* line */ (const char *) " vv+vv  vvsvv ",
           /* line */ (const char *) " v...v  v...v ",
           /* line */ (const char *) " v.$.v  v.$.v ",
           /* line */ (const char *) " vvvvv  vvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " vvv.vvvvv ",
           /* line */ (const char *) " v......$v ",
           /* line */ (const char *) " v.....M.v ",
           /* line */ (const char *) "^..vvvv..v ",
           /* line */ (const char *) " v.v.Ev..v ",
           /* line */ (const char *) " v.v..v..v ",
           /* line */ (const char *) " v.vv+v...^",
           /* line */ (const char *) " v.......v ",
           /* line */ (const char *) " vvvvvv.vv ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " vvv.vvvvv ",
           /* line */ (const char *) " v......$v ",
           /* line */ (const char *) " v.vvv.M.v ",
           /* line */ (const char *) "^..vEv...v ",
           /* line */ (const char *) " v.v+v...v ",
           /* line */ (const char *) " v....CCCv ",
           /* line */ (const char *) " v....C...^",
           /* line */ (const char *) " v....C..v ",
           /* line */ (const char *) " vvvvvv.vv ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " vvv.vvvvv ",
           /* line */ (const char *) " v.......v ",
           /* line */ (const char *) " v..M....v ",
           /* line */ (const char *) "^........v ",
           /* line */ (const char *) " v.......v ",
           /* line */ (const char *) " v..vvvv+v ",
           /* line */ (const char *) " v..vE...v ",
           /* line */ (const char *) " v..v...$v ",
           /* line */ (const char *) " vvvvvvvvv ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " vvv.vvvvv ",
           /* line */ (const char *) " v.......v ",
           /* line */ (const char *) " v..M....v ",
           /* line */ (const char *) " v.......v ",
           /* line */ (const char *) " v+vvvvvvv ",
           /* line */ (const char *) " v.......v ",
           /* line */ (const char *) " v...E...v ",
           /* line */ (const char *) " v......$v ",
           /* line */ (const char *) " vvvvvvvvv ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) "   v.vvvvv ",
           /* line */ (const char *) "   v......^",
           /* line */ (const char *) "   v..M..v ",
           /* line */ (const char *) " vvv+vvvvv ",
           /* line */ (const char *) " v.......v ",
           /* line */ (const char *) " v.......v ",
           /* line */ (const char *) " v...E...v ",
           /* line */ (const char *) " v......$v ",
           /* line */ (const char *) " vvvvvvvvv ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) "   v.vvvvv ",
           /* line */ (const char *) "   v......^",
           /* line */ (const char *) "   v+vvvvv ",
           /* line */ (const char *) " vvv.....v ",
           /* line */ (const char *) " v...M...v ",
           /* line */ (const char *) " v.......v ",
           /* line */ (const char *) " v...E...v ",
           /* line */ (const char *) " v......$v ",
           /* line */ (const char *) " vvvvvvvvv ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) "   v.vvv   ",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   v...vvv ",
           /* line */ (const char *) " vvv.....v ",
           /* line */ (const char *) " v....M..v ",
           /* line */ (const char *) "^........v ",
           /* line */ (const char *) " v...E...v ",
           /* line */ (const char *) " v......$v ",
           /* line */ (const char *) " vvvvvvvvv ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) "   v.vvv   ",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   v...vvv ",
           /* line */ (const char *) " vvv.M...v ",
           /* line */ (const char *) "^..C.....v ",
           /* line */ (const char *) " v$C.....v ",
           /* line */ (const char *) " vvv.E...v ",
           /* line */ (const char *) "   v.....v ",
           /* line */ (const char *) "   vvvvvvv ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) "   v.vvv   ",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   v.M.vvv ",
           /* line */ (const char *) " vvv...C..^",
           /* line */ (const char *) "^..C...C$v ",
           /* line */ (const char *) " v$C...vvv ",
           /* line */ (const char *) " vvv.E.v   ",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   vvvvv   ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) "   v.vvv   ",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   v...vvv ",
           /* line */ (const char *) "   v.....v ",
           /* line */ (const char *) "   v.M...v ",
           /* line */ (const char *) "   v...vvv ",
           /* line */ (const char *) "   v.E.v   ",
           /* line */ (const char *) "   v..$v   ",
           /* line */ (const char *) "   v.vvv   ",
           /* line */ (const char *) "    ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " vvv.vvvvv ",
           /* line */ (const char *) "^.........^",
           /* line */ (const char *) " vvv.M.vvv ",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   v.E.v   ",
           /* line */ (const char *) "   v..$v   ",
           /* line */ (const char *) "   vvvvv   ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^      ",
           /* line */ (const char *) "  vvv.vvvvv ",
           /* line */ (const char *) "  v.......vv",
           /* line */ (const char *) " vv.v.v.v..v",
           /* line */ (const char *) "^..........v",
           /* line */ (const char *) " vv.v.M....v",
           /* line */ (const char *) "  v.....E..v",
           /* line */ (const char *) "  v.v......v",
           /* line */ (const char *) "  v.......$v",
           /* line */ (const char *) "  vvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^        ",
           /* line */ (const char *) "v.vvvvvvv ",
           /* line */ (const char *) "v........^",
           /* line */ (const char *) "vv.M...vv ",
           /* line */ (const char *) " v......v ",
           /* line */ (const char *) " v......v ",
           /* line */ (const char *) " vv...E.v ",
           /* line */ (const char *) "  vv...$v ",
           /* line */ (const char *) "  vvvvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^  ",
           /* line */ (const char *) "     v.v ",
           /* line */ (const char *) "     v.v ",
           /* line */ (const char *) "    vv.vv",
           /* line */ (const char *) "    vB.Bv",
           /* line */ (const char *) "vvvvv...v",
           /* line */ (const char *) "v.......v",
           /* line */ (const char *) "v....M..v",
           /* line */ (const char *) "v.E.....v",
           /* line */ (const char *) "v$......v",
           /* line */ (const char *) "vvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^  ",
           /* line */ (const char *) "     v.v ",
           /* line */ (const char *) "     v.v ",
           /* line */ (const char *) "    vv.vv",
           /* line */ (const char *) "    v|.|v",
           /* line */ (const char *) "    v...v",
           /* line */ (const char *) "    v|.|v",
           /* line */ (const char *) "    v...v",
           /* line */ (const char *) "vvvvv|.|v",
           /* line */ (const char *) "v.......v",
           /* line */ (const char *) "v....M..v",
           /* line */ (const char *) "v.E.....v",
           /* line */ (const char *) "v$......v",
           /* line */ (const char *) "vvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^  ",
           /* line */ (const char *) "     v.v ",
           /* line */ (const char *) "     v.v ",
           /* line */ (const char *) "    vv.vv",
           /* line */ (const char *) "    vC.Cv",
           /* line */ (const char *) "    v...v",
           /* line */ (const char *) "    vC.Cv",
           /* line */ (const char *) "    v...v",
           /* line */ (const char *) "vvvvvC.Cv",
           /* line */ (const char *) "v.......v",
           /* line */ (const char *) "v.....M.v",
           /* line */ (const char *) "v.E.....v",
           /* line */ (const char *) "v$......v",
           /* line */ (const char *) "vvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^  ",
           /* line */ (const char *) "     v.v ",
           /* line */ (const char *) "     v.v ",
           /* line */ (const char *) "    vv.vv",
           /* line */ (const char *) "    vB.Bv",
           /* line */ (const char *) "    v...v",
           /* line */ (const char *) "vvvvvB.Bv",
           /* line */ (const char *) "v.......v",
           /* line */ (const char *) "v.....M.v",
           /* line */ (const char *) "v.E.....v",
           /* line */ (const char *) "v$......v",
           /* line */ (const char *) "vvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^         ",
           /* line */ (const char *) "v.vvvvvvvv ",
           /* line */ (const char *) "v.........^",
           /* line */ (const char *) "v.cCCc.vvv ",
           /* line */ (const char *) "v.CCCC.v   ",
           /* line */ (const char *) "v...CC.vvv ",
           /* line */ (const char *) "vv..CC...v ",
           /* line */ (const char *) " v..cC.E.v ",
           /* line */ (const char *) " v.M....$v ",
           /* line */ (const char *) " vvvvvvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) " vvvv.vvvv ",
           /* line */ (const char *) " v..BMB..v ",
           /* line */ (const char *) " v.......v ",
           /* line */ (const char *) " v.......v ",
           /* line */ (const char *) " v...E..$v ",
           /* line */ (const char *) " vvvvvvvvv ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^          ",
           /* line */ (const char *) " vvvv.vvvvvvvvvv",
           /* line */ (const char *) " v..B.B..s....Bv",
           /* line */ (const char *) " v.......v..$..v",
           /* line */ (const char *) " v.......vB...Bv",
           /* line */ (const char *) " v.......vvvvvvv",
           /* line */ (const char *) " vvvvvvCCv      ",
           /* line */ (const char *) "      v..vvvvvv ",
           /* line */ (const char *) "      v.......v ",
           /* line */ (const char *) "      v....M..v ",
           /* line */ (const char *) "      v.......v ",
           /* line */ (const char *) "      v...E..$v ",
           /* line */ (const char *) "      vvvvvvvvv ",
           /* line */ (const char *) "                ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^          ",
           /* line */ (const char *) " vvvv.vvvv      ",
           /* line */ (const char *) " v.......v      ",
           /* line */ (const char *) " v.......v      ",
           /* line */ (const char *) " v.......v      ",
           /* line */ (const char *) " v.......v      ",
           /* line */ (const char *) " vvvvvvCCv      ",
           /* line */ (const char *) "      v..vvvvvv ",
           /* line */ (const char *) "      v.......v ",
           /* line */ (const char *) "      v....M..v ",
           /* line */ (const char *) "      v.......v ",
           /* line */ (const char *) "      v...E..$v ",
           /* line */ (const char *) "      vvvvvvvvv ",
           /* line */ (const char *) "                ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^          ",
           /* line */ (const char *) " vvvv.vvvv      ",
           /* line */ (const char *) " v.......v      ",
           /* line */ (const char *) " v.......v      ",
           /* line */ (const char *) " v.......v      ",
           /* line */ (const char *) " vvvvCCCCv      ",
           /* line */ (const char *) "    v....vvvvvv ",
           /* line */ (const char *) "    v.........v ",
           /* line */ (const char *) "    v......G..v ",
           /* line */ (const char *) "    v.........v ",
           /* line */ (const char *) "    v.....E..$v ",
           /* line */ (const char *) "    vvvvvvvvvvv ",
           /* line */ (const char *) "                ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^          ",
           /* line */ (const char *) " vvvv.vvvv      ",
           /* line */ (const char *) " v.......v      ",
           /* line */ (const char *) " v.......v      ",
           /* line */ (const char *) " vvvvvv..v      ",
           /* line */ (const char *) "      vCCv      ",
           /* line */ (const char *) "      v..vvvvvv ",
           /* line */ (const char *) "      v.......v ",
           /* line */ (const char *) "      v.......v ",
           /* line */ (const char *) "      v.......v ",
           /* line */ (const char *) "      v.M.E.$.v ",
           /* line */ (const char *) "      vvvvvvvvv ",
           /* line */ (const char *) "                ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^          ",
           /* line */ (const char *) " vvvv.vvvvv     ",
           /* line */ (const char *) " v....C...vv    ",
           /* line */ (const char *) " v....C....vv   ",
           /* line */ (const char *) " vvvvvv..M..vv  ",
           /* line */ (const char *) "      v......vv ",
           /* line */ (const char *) "      v.......v ",
           /* line */ (const char *) "      v.......v ",
           /* line */ (const char *) "      v...E.$.v ",
           /* line */ (const char *) "      vvvvvvvvv ",
           /* line */ (const char *) "                ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^         ",
           /* line */ (const char *) " v.vvvv     ",
           /* line */ (const char *) " v....vv    ",
           /* line */ (const char *) " v.....vv   ",
           /* line */ (const char *) " v..M...v   ",
           /* line */ (const char *) "^.......vv  ",
           /* line */ (const char *) " vv......vv ",
           /* line */ (const char *) "  v.......v ",
           /* line */ (const char *) "  vv...E..v ",
           /* line */ (const char *) "    vv...$v ",
           /* line */ (const char *) "     vvvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "  vvv.vvv  ",
           /* line */ (const char *) "  v.....v  ",
           /* line */ (const char *) " vv..M..v  ",
           /* line */ (const char *) "^.......v  ",
           /* line */ (const char *) " vvv....vvv",
           /* line */ (const char *) "   vv.....v",
           /* line */ (const char *) "    v..E..v",
           /* line */ (const char *) "    v....$v",
           /* line */ (const char *) "    vvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^      ",
           /* line */ (const char *) "      vv.vvvv  ",
           /* line */ (const char *) "     vv.....vv ",
           /* line */ (const char *) "  vvvv.......v ",
           /* line */ (const char *) " vv...........^",
           /* line */ (const char *) "^............v ",
           /* line */ (const char *) " v...M....E..v ",
           /* line */ (const char *) " v..........vv ",
           /* line */ (const char *) " vv...$vvvvvv  ",
           /* line */ (const char *) "  vvvvvv       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^      ",
           /* line */ (const char *) "      vv.vvvv  ",
           /* line */ (const char *) "      v.....vv ",
           /* line */ (const char *) " vvvvv.......v ",
           /* line */ (const char *) " v......M....v ",
           /* line */ (const char *) " v..E.......vv ",
           /* line */ (const char *) " vv...$vvvvvv  ",
           /* line */ (const char *) "  vvvvvv       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  vvvvvv  ",
           /* line */ (const char *) "  v....v  ",
           /* line */ (const char *) " v......v ",
           /* line */ (const char *) " v..M....^",
           /* line */ (const char *) "^.......v ",
           /* line */ (const char *) " v....E.v ",
           /* line */ (const char *) " vv....$v ",
           /* line */ (const char *) "  vvvvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^   ",
           /* line */ (const char *) "   vvvvvv.vv ",
           /* line */ (const char *) "  vv.......v ",
           /* line */ (const char *) "  v........v ",
           /* line */ (const char *) " vv.........^",
           /* line */ (const char *) " v...M....vv ",
           /* line */ (const char *) " v.......vv  ",
           /* line */ (const char *) " v...E...v   ",
           /* line */ (const char *) " v......$v   ",
           /* line */ (const char *) " vvvvvvvvv   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^ ",
           /* line */ (const char *) "        v.v",
           /* line */ (const char *) "        v.v",
           /* line */ (const char *) "        v.v",
           /* line */ (const char *) "vvvvvvvvv.v",
           /* line */ (const char *) "v$........v",
           /* line */ (const char *) "v.........v",
           /* line */ (const char *) "v.E.......v",
           /* line */ (const char *) "v.....M...v",
           /* line */ (const char *) "vvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   vvvvv     ",
           /* line */ (const char *) "  vv...v     ",
           /* line */ (const char *) " vv....vvvvv ",
           /* line */ (const char *) " v..M..C....^",
           /* line */ (const char *) " v.....vvvvv ",
           /* line */ (const char *) " v.....v     ",
           /* line */ (const char *) " v..E..v     ",
           /* line */ (const char *) " v$....v     ",
           /* line */ (const char *) " vvvvvvv     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "  vvv.vvvvv",
           /* line */ (const char *) "  v``.~~.$v",
           /* line */ (const char *) " vv`..B~~~v",
           /* line */ (const char *) "^........Ev",
           /* line */ (const char *) " vv...B~~~v",
           /* line */ (const char *) "  v$...~~.v",
           /* line */ (const char *) " vvvvvvvvsv",
           /* line */ (const char *) " vC..$CCC.v",
           /* line */ (const char *) " vCm..CCC.v",
           /* line */ (const char *) " vCCCCCCCCv",
           /* line */ (const char *) " vvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "  vvv.vvvv ",
           /* line */ (const char *) "vvv..C.C$v ",
           /* line */ (const char *) "v$.....CCv ",
           /* line */ (const char *) "v........v ",
           /* line */ (const char *) "v.M..CCCCv ",
           /* line */ (const char *) "v....C..vv ",
           /* line */ (const char *) "vCC..C.Ev  ",
           /* line */ (const char *) "vCCC.vvvv  ",
           /* line */ (const char *) "v..C.v     ",
           /* line */ (const char *) "v$.CCv     ",
           /* line */ (const char *) "vvvvvv     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ..$   ..M ",
           /* line */ (const char *) " ...   ... ",
           /* line */ (const char *) " T..   T.. ",
           /* line */ (const char *) "           ",
           /* line */ (const char *) "   vvvvvvvv",
           /* line */ (const char *) "   v......v",
           /* line */ (const char *) "   v.E....v",
           /* line */ (const char *) "   v......v",
           /* line */ (const char *) "vvvv......v",
           /* line */ (const char *) "v..s.M....v",
           /* line */ (const char *) "v..v......v",
           /* line */ (const char *) "v..v......v",
           /* line */ (const char *) "v$.v......v",
           /* line */ (const char *) "vvvv|.|vvvv",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   v|.|v   ",
           /* line */ (const char *) "     ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   vvvvv   ",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   v.E.v   ",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "  vvCCCvv  ",
           /* line */ (const char *) " vv.....vv ",
           /* line */ (const char *) "vvB..M..Bvv",
           /* line */ (const char *) "v.........v",
           /* line */ (const char *) "v.........v",
           /* line */ (const char *) "v$........v",
           /* line */ (const char *) "vvvv|.|vvvv",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   v|.|v   ",
           /* line */ (const char *) "     ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   vvvvv   ",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   v.E.v   ",
           /* line */ (const char *) "  vv...vv  ",
           /* line */ (const char *) " vvB...Bvv ",
           /* line */ (const char *) "vv...M...vv",
           /* line */ (const char *) "vB.......Bv",
           /* line */ (const char *) "v.........v",
           /* line */ (const char *) "vG.......Gv",
           /* line */ (const char *) "vvvvB.Bvvvv",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   vB.Bv   ",
           /* line */ (const char *) "     ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   vvvvv   ",
           /* line */ (const char *) "   v$..v   ",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   vvvsv   ",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   v.E.v   ",
           /* line */ (const char *) "  vv...vv  ",
           /* line */ (const char *) " vvB...Bvv ",
           /* line */ (const char *) "vv...M...vv",
           /* line */ (const char *) "vB.......Bv",
           /* line */ (const char *) "v.........v",
           /* line */ (const char *) "vG.......Gv",
           /* line */ (const char *) "vvvvB.Bvvvv",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   vB.Bv   ",
           /* line */ (const char *) "     ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   vvvvv   ",
           /* line */ (const char *) "   v$.$v   ",
           /* line */ (const char *) "   v.E.v   ",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "  vvv+vvv  ",
           /* line */ (const char *) " vvB...Bvv ",
           /* line */ (const char *) "vvB.....Bvv",
           /* line */ (const char *) "vB.......Bv",
           /* line */ (const char *) "v.........v",
           /* line */ (const char *) "v..G...G..v",
           /* line */ (const char *) "v.........v",
           /* line */ (const char *) "v.........v",
           /* line */ (const char *) "vvvvB.Bvvvv",
           /* line */ (const char *) "   v...v   ",
           /* line */ (const char *) "   vB.Bv   ",
           /* line */ (const char *) "     ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvvvv     ",
           /* line */ (const char *) "v......v     ",
           /* line */ (const char *) "v.M....v     ",
           /* line */ (const char *) "v....v.v     ",
           /* line */ (const char *) "v.$..v.v     ",
           /* line */ (const char *) "v....vsvvvvv ",
           /* line */ (const char *) "vsvvvv......^",
           /* line */ (const char *) "v...$vvvvv.v ",
           /* line */ (const char *) "vvvvvv   v.v ",
           /* line */ (const char *) "vE..|vvvvv.v ",
           /* line */ (const char *) "v..........v ",
           /* line */ (const char *) "v$..|vvvvvvv ",
           /* line */ (const char *) "vvvvvv       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvv       ",
           /* line */ (const char *) "vM..|vvvvvvv ",
           /* line */ (const char *) "v....s.....v ",
           /* line */ (const char *) "v$..|vvvvv.v ",
           /* line */ (const char *) "vvvvvv   v..^",
           /* line */ (const char *) "vE..|vvvvv.v ",
           /* line */ (const char *) "v....+.....v ",
           /* line */ (const char *) "v$..|vvvvvvv ",
           /* line */ (const char *) "vvvvvv       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvv       ",
           /* line */ (const char *) "v...|vvvvvvv ",
           /* line */ (const char *) "v....s.....v ",
           /* line */ (const char *) "v$..|vvvvv.v ",
           /* line */ (const char *) "vvvsvv   v.v ",
           /* line */ (const char *) "  v.v    v.v ",
           /* line */ (const char *) "  v.v    vsv ",
           /* line */ (const char *) "vvvsvv   v..^",
           /* line */ (const char *) "vE..|vvvvv.v ",
           /* line */ (const char *) "v....+.....v ",
           /* line */ (const char *) "v...|vvvvvvv ",
           /* line */ (const char *) "v....v       ",
           /* line */ (const char *) "vM...v       ",
           /* line */ (const char *) "vvvvvv       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvv       ",
           /* line */ (const char *) "vM...vvvvvvv ",
           /* line */ (const char *) "v..........v ",
           /* line */ (const char *) "v....vvvvv.v ",
           /* line */ (const char *) "vB...v   v..^",
           /* line */ (const char *) "vE...vvvvv.v ",
           /* line */ (const char *) "vB.........v ",
           /* line */ (const char *) "v$...vvvvvvv ",
           /* line */ (const char *) "vvvvvv       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvv       ",
           /* line */ (const char *) "vM...vvvvvvv ",
           /* line */ (const char *) "v....C.....v ",
           /* line */ (const char *) "v....C..CCCv ",
           /* line */ (const char *) "vB...C..C...^",
           /* line */ (const char *) "vE...C..CCCv ",
           /* line */ (const char *) "vB...C.....v ",
           /* line */ (const char *) "v$...vvvvvvv ",
           /* line */ (const char *) "vvvvvv       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvv       ",
           /* line */ (const char *) "vM...vvvvvvv ",
           /* line */ (const char *) "v.....~~~~~v ",
           /* line */ (const char *) "v....~~~~~~v ",
           /* line */ (const char *) "vB...~~~~~~.^",
           /* line */ (const char *) "vE...~~~~~~v ",
           /* line */ (const char *) "vB....~~~~~v ",
           /* line */ (const char *) "v$...vvvvvvv ",
           /* line */ (const char *) "vvvvvv       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^   ",
           /* line */ (const char *) "  vvvvvv.vvv",
           /* line */ (const char *) "  v........v",
           /* line */ (const char *) " vv..~~..v.v",
           /* line */ (const char *) "^...~~~~...v",
           /* line */ (const char *) " vv..~~....v",
           /* line */ (const char *) "  v...~~~~.v",
           /* line */ (const char *) " vv......~~v",
           /* line */ (const char *) " v~~~.....~v",
           /* line */ (const char *) " v~........v",
           /* line */ (const char *) " v...|E|.M.v",
           /* line */ (const char *) " v$........v",
           /* line */ (const char *) " vvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^   ",
           /* line */ (const char *) "  vvvvvv.vvv",
           /* line */ (const char *) "  v........v",
           /* line */ (const char *) " vv........v",
           /* line */ (const char *) "^..........v",
           /* line */ (const char *) " vv........v",
           /* line */ (const char *) "  v........v",
           /* line */ (const char *) " vvvCCCCCvvv",
           /* line */ (const char *) " v.........v",
           /* line */ (const char *) " v.........v",
           /* line */ (const char *) " v...|E|.M.v",
           /* line */ (const char *) " v.........v",
           /* line */ (const char *) " v.........v",
           /* line */ (const char *) " vvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^   ",
           /* line */ (const char *) "   vvvvv.vv ",
           /* line */ (const char *) "   v......v ",
           /* line */ (const char *) " vvv.~~..vv ",
           /* line */ (const char *) "^....~~~...^",
           /* line */ (const char *) " vv..~~..vv ",
           /* line */ (const char *) "  v......$v ",
           /* line */ (const char *) " vvvv.t.vvv ",
           /* line */ (const char *) " v..v|E|..v ",
           /* line */ (const char *) " v$.s..M..v ",
           /* line */ (const char *) " vvvvvvvvvv ",

           nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "  vvv.vvvvv",
           /* line */ (const char *) "  v``.~~.$v",
           /* line */ (const char *) " vv`..B~~~v",
           /* line */ (const char *) "^...G....Ev",
           /* line */ (const char *) " vv...B~~~v",
           /* line */ (const char *) "  v$...~~.v",
           /* line */ (const char *) " vvvvvvvvsv",
           /* line */ (const char *) " vC..$CCC.v",
           /* line */ (const char *) " vCm..CCC.v",
           /* line */ (const char *) " vCCCCCCCCv",
           /* line */ (const char *) " vvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "  vvv.v    ",
           /* line */ (const char *) "  v...vvvvv",
           /* line */ (const char *) " vv...BCCCv",
           /* line */ (const char *) "^...G....Ev",
           /* line */ (const char *) " vv...BCCCv",
           /* line */ (const char *) "  v$..vvvvv",
           /* line */ (const char *) " vvvvsv    ",
           /* line */ (const char *) " v....v    ",
           /* line */ (const char *) " v.m..v    ",
           /* line */ (const char *) " v$...v    ",
           /* line */ (const char *) " vvvvvv    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "  vvv.v    ",
           /* line */ (const char *) "  v...vvvvv",
           /* line */ (const char *) " vv...BCCCv",
           /* line */ (const char *) "^...G....Ev",
           /* line */ (const char *) " vv...BCCCv",
           /* line */ (const char *) "  v$..vvvvv",
           /* line */ (const char *) " vvvvsv...v",
           /* line */ (const char *) " v..B.B...v",
           /* line */ (const char *) " v......M.v",
           /* line */ (const char *) " v.......$v",
           /* line */ (const char *) " vvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "  vvv.v    ",
           /* line */ (const char *) "  v...vvvvv",
           /* line */ (const char *) " vv...BCCCv",
           /* line */ (const char *) "^........Ev",
           /* line */ (const char *) " vv...BCCCv",
           /* line */ (const char *) "  vLL.vvvvv",
           /* line */ (const char *) " vvLLLL...v",
           /* line */ (const char *) " vLLL.....v",
           /* line */ (const char *) " v......M.v",
           /* line */ (const char *) " v.......$v",
           /* line */ (const char *) " vvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "  vvv.v    ",
           /* line */ (const char *) "  v...vvvvv",
           /* line */ (const char *) " vv...BCCCv",
           /* line */ (const char *) "^...G....Ev",
           /* line */ (const char *) " vv...BCCCv",
           /* line */ (const char *) "  vL..vvvvv",
           /* line */ (const char *) "  vLL.v    ",
           /* line */ (const char *) "  vLLLv    ",
           /* line */ (const char *) "  vLLLv    ",
           /* line */ (const char *) "  v..Lv    ",
           /* line */ (const char *) "  v...v    ",
           /* line */ (const char *) "  v.$.v    ",
           /* line */ (const char *) "  vvvvv    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "  vvv.v    ",
           /* line */ (const char *) "  v...vvvvv",
           /* line */ (const char *) " vv...BCCCv",
           /* line */ (const char *) "^...G....Ev",
           /* line */ (const char *) " vv...BCCCv",
           /* line */ (const char *) "  vC..vvvvv",
           /* line */ (const char *) "  vCC.v    ",
           /* line */ (const char *) "  vCCCv    ",
           /* line */ (const char *) "  vCCCv    ",
           /* line */ (const char *) "  v..Cv    ",
           /* line */ (const char *) "  v...v    ",
           /* line */ (const char *) "  v.$.v    ",
           /* line */ (const char *) "  vvvvv    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^      ",
           /* line */ (const char *) "  vvv.vvvvvv",
           /* line */ (const char *) "  v........v",
           /* line */ (const char *) " vv.....B.Bv",
           /* line */ (const char *) "^.....M..E.v",
           /* line */ (const char *) " vv.....B.Bv",
           /* line */ (const char *) "  v........v",
           /* line */ (const char *) "  vvvsvvvsvv",
           /* line */ (const char *) "  v....v...v",
           /* line */ (const char *) "  v..G.s.$.v",
           /* line */ (const char *) "  v$...v...v",
           /* line */ (const char *) "  vvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) " vvvv.vv   ",
           /* line */ (const char *) "^...C..vvvv",
           /* line */ (const char *) " vvvv.....v",
           /* line */ (const char *) "    v....$v",
           /* line */ (const char *) "    v.LL.vv",
           /* line */ (const char *) "    v.LL.v ",
           /* line */ (const char *) "    vM..Ev ",
           /* line */ (const char *) "    vvvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^    ",
           /* line */ (const char *) " vvvv.vv  ",
           /* line */ (const char *) "^...C..vvv",
           /* line */ (const char *) " vvvv....v",
           /* line */ (const char *) "    v....v",
           /* line */ (const char *) "    v.LL.v",
           /* line */ (const char *) "    v.LL.v",
           /* line */ (const char *) "    v....v",
           /* line */ (const char *) "    v.LL.v",
           /* line */ (const char *) "    v.LL.v",
           /* line */ (const char *) "    v....v",
           /* line */ (const char *) "    vM..Ev",
           /* line */ (const char *) "    vvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvvvv",
           /* line */ (const char *) " vLL.E.LLLLv",
           /* line */ (const char *) " vLL...LLL.v",
           /* line */ (const char *) " v.LL.LL.v.v",
           /* line */ (const char *) " v.LLMLLvv.v",
           /* line */ (const char *) " v..LLL.vv.v",
           /* line */ (const char *) " vvvv.vv.v.v",
           /* line */ (const char *) "^.....vvvv.v",
           /* line */ (const char *) " vvM.......v",
           /* line */ (const char *) "  v$..LLLLLv",
           /* line */ (const char *) "  vvv.vvvvvv",
           /* line */ (const char *) "     ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^ ",
           /* line */ (const char *) "  vvvvvvv.v",
           /* line */ (const char *) "  v.......v",
           /* line */ (const char *) "  v...g...v",
           /* line */ (const char *) "  v.......v",
           /* line */ (const char *) "  vvvvvCvvv",
           /* line */ (const char *) "  v$....vvv",
           /* line */ (const char *) " vv..CCCCCv",
           /* line */ (const char *) "^....C.M.Ev",
           /* line */ (const char *) " vv..C.C.Cv",
           /* line */ (const char *) "  vvvv.C.vv",
           /* line */ (const char *) "    v....v ",
           /* line */ (const char *) "    v.vvvv ",
           /* line */ (const char *) "     ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^       ",
           /* line */ (const char *) "  v.vvvvvv ",
           /* line */ (const char *) "  v......v ",
           /* line */ (const char *) " vv|LL...v ",
           /* line */ (const char *) "^...LLL.$v ",
           /* line */ (const char *) " vv|LL...v ",
           /* line */ (const char *) "  v.....gv ",
           /* line */ (const char *) "  vv...vvv ",
           /* line */ (const char *) "   vB.Bv   ",
           /* line */ (const char *) "   vBEBv   ",
           /* line */ (const char *) "   vvvvv   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^  ",
           /* line */ (const char *) "  vvvvvv.vv",
           /* line */ (const char *) "  v$.L....v",
           /* line */ (const char *) "  v.LLLLL.v",
           /* line */ (const char *) " vvLLLLLLLv",
           /* line */ (const char *) "^.........v",
           /* line */ (const char *) " vvLLLLLLLv",
           /* line */ (const char *) "  v.......v",
           /* line */ (const char *) "  vsvvvvvsv",
           /* line */ (const char *) "  v.vvEvv.v",
           /* line */ (const char *) "  v.vvCvv.v",
           /* line */ (const char *) "  v$..C..mv",
           /* line */ (const char *) "  vvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^  ",
           /* line */ (const char *) "  vvvvvv.vv",
           /* line */ (const char *) "  v$.C....v",
           /* line */ (const char *) "  v.CCCCC.v",
           /* line */ (const char *) " vvCCCCCCCv",
           /* line */ (const char *) " vv.CCCCC.v",
           /* line */ (const char *) "^.........v",
           /* line */ (const char *) " vvCCCCCCCv",
           /* line */ (const char *) "  v.......v",
           /* line */ (const char *) "  vsvvvvvsv",
           /* line */ (const char *) "  v.vvEvv.v",
           /* line */ (const char *) "  v.vvCvv.v",
           /* line */ (const char *) "  v$..C..mv",
           /* line */ (const char *) "  vvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "   vL=Lv   ",
           /* line */ (const char *) "   vL=Lv   ",
           /* line */ (const char *) "vvvvL=Lvvv ",
           /* line */ (const char *) "v$..L=L...^",
           /* line */ (const char *) "v...L=L..v ",
           /* line */ (const char *) "v........v ",
           /* line */ (const char *) "vvv..M..vv ",
           /* line */ (const char *) "  v..E..v  ",
           /* line */ (const char *) "  vvvvvvv  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  vvvvvvv   ",
           /* line */ (const char *) "  vvLMLvv   ",
           /* line */ (const char *) "  vLL.LLv   ",
           /* line */ (const char *) " vvLL.LLvv  ",
           /* line */ (const char *) " LLL...LLvvv",
           /* line */ (const char *) "^........s.v",
           /* line */ (const char *) " LLL...LLv.v",
           /* line */ (const char *) " vvLL.LLvv.v",
           /* line */ (const char *) "  vLL.LLvv.v",
           /* line */ (const char *) "  vvL.Lvvv.v",
           /* line */ (const char *) "   vELLv$..v",
           /* line */ (const char *) "   vvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvv ",
           /* line */ (const char *) " vCCCCCCCv ",
           /* line */ (const char *) " vC$....Cvv",
           /* line */ (const char *) " vC..CCCCCv",
           /* line */ (const char *) "^....C...Ev",
           /* line */ (const char *) " vC..CCCCCv",
           /* line */ (const char *) " vC....MCvv",
           /* line */ (const char *) " vCCCCCCCv ",
           /* line */ (const char *) " vvvvvvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvvv",
           /* line */ (const char *) " vCCC.CCCCv",
           /* line */ (const char *) "^....t...Ev",
           /* line */ (const char *) " vCCCCCCCCv",
           /* line */ (const char *) " vvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvvv",
           /* line */ (const char *) " vLLLLLLLLv",
           /* line */ (const char *) "^.......tEv",
           /* line */ (const char *) " vLLLLLL.Lv",
           /* line */ (const char *) " vvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "  vvv.vvvvv",
           /* line */ (const char *) "  v....L..v",
           /* line */ (const char *) " vvLLLLLLLv",
           /* line */ (const char *) "^...L....gv",
           /* line */ (const char *) " vvLLL.LLLv",
           /* line */ (const char *) "  v.......v",
           /* line */ (const char *) "  v+vvvvvvv",
           /* line */ (const char *) "  v..v...$v",
           /* line */ (const char *) "  v..s....v",
           /* line */ (const char *) "  vvvv.M..v",
           /* line */ (const char *) "     v....v",
           /* line */ (const char *) "     v...Ev",
           /* line */ (const char *) "     vvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "    v.v    ",
           /* line */ (const char *) "vvvvC.Cvvvv",
           /* line */ (const char *) "vCCCCtCCCCv",
           /* line */ (const char *) "vCB.....BCv",
           /* line */ (const char *) "vC...g...Cv",
           /* line */ (const char *) "vCB.....BCv",
           /* line */ (const char *) "vCCCC.CCCCv",
           /* line */ (const char *) "vvvvCECvvvv",
           /* line */ (const char *) "   vC.Cv   ",
           /* line */ (const char *) "   vCCCv   ",
           /* line */ (const char *) "   vC.Cvvvv",
           /* line */ (const char *) "   vC$C.s$v",
           /* line */ (const char *) "   vvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvvvvvvv   ",
           /* line */ (const char *) "vE.LL....$v   ",
           /* line */ (const char *) "v...LL..b.v   ",
           /* line */ (const char *) "vLLLLLL...vvvv",
           /* line */ (const char *) "v............v",
           /* line */ (const char *) "vtLLLLLLLLLLLv",
           /* line */ (const char *) "v.LLLLLLLLLL.v",
           /* line */ (const char *) "v.......m....v",
           /* line */ (const char *) "vvvvv.vvvvvvvv",
           /* line */ (const char *) "     ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvvvvv ",
           /* line */ (const char *) "    vM...$$v ",
           /* line */ (const char *) "    vvsvvvvv ",
           /* line */ (const char *) "    vB.B...v ",
           /* line */ (const char *) "  vvv.......^",
           /* line */ (const char *) " vv.LL.....v ",
           /* line */ (const char *) "^..gLLLLL..v ",
           /* line */ (const char *) " v...LL....v ",
           /* line */ (const char *) " v....L..vvv ",
           /* line */ (const char *) " v$.....vv   ",
           /* line */ (const char *) " v.....Ev    ",
           /* line */ (const char *) " vvvvvvvv    ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvvvv",
           /* line */ (const char *) " v$....L..Bv",
           /* line */ (const char *) " v....L..M.v",
           /* line */ (const char *) " v...LL....v",
           /* line */ (const char *) "^...LLLLL..v",
           /* line */ (const char *) " vvvvvvvv.vv",
           /* line */ (const char *) " v....vLLLLv",
           /* line */ (const char *) " v.$$.s....v",
           /* line */ (const char *) " v....v..E.v",
           /* line */ (const char *) " vvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^        ",
           /* line */ (const char *) " vv.vvvvvvvv",
           /* line */ (const char *) "^......L..Bv",
           /* line */ (const char *) " v....L....v",
           /* line */ (const char *) " v...LL....v",
           /* line */ (const char *) " v..LLLLL..v",
           /* line */ (const char *) " vvvv.g.vv.v",
           /* line */ (const char *) " v..vvvvvv.v",
           /* line */ (const char *) " v$.s..M...v",
           /* line */ (const char *) " vvvv.LLL.vv",
           /* line */ (const char *) "    v.LEL.v ",
           /* line */ (const char *) "    vvvvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^      ",
           /* line */ (const char *) "vvvvv.vvvvv ",
           /* line */ (const char *) "v$.$v.v.$.v ",
           /* line */ (const char *) "vLLLv.vLLLv ",
           /* line */ (const char *) "v...s.s..mv ",
           /* line */ (const char *) "v.M.v.v.E.v ",
           /* line */ (const char *) "v...vLv..$v ",
           /* line */ (const char *) "v...v.+.vvvv",
           /* line */ (const char *) "v...v.vsv.$v",
           /* line */ (const char *) "v...vLv.L..v",
           /* line */ (const char *) "vvvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvvvvvvv",
           /* line */ (const char *) "v...~~...Bv",
           /* line */ (const char *) "v..vv~~...v",
           /* line */ (const char *) "v.vv~~~...v",
           /* line */ (const char *) "v.v~~$~~..v",
           /* line */ (const char *) "v.vv~~....v",
           /* line */ (const char *) "v..vv~....v",
           /* line */ (const char *) "vE..v.....v",
           /* line */ (const char *) "vvvvv.vvvvv",
           /* line */ (const char *) "     ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvvvvvvv",
           /* line */ (const char *) "vE~~~....Bv",
           /* line */ (const char *) "v~~~~~~...v",
           /* line */ (const char *) "v~~~~~~...v",
           /* line */ (const char *) "v~~~~~~~..v",
           /* line */ (const char *) "v~~~~~....v",
           /* line */ (const char *) "v~v~~.....v",
           /* line */ (const char *) "v$v~......v",
           /* line */ (const char *) "vvvvv.vvvvv",
           /* line */ (const char *) "     ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^    ",
           /* line */ (const char *) "vvvvvvv.vvv ",
           /* line */ (const char *) "vB.......Bv ",
           /* line */ (const char *) "v....C.....^",
           /* line */ (const char *) "v...CC....v ",
           /* line */ (const char *) "v..CCCCC..v ",
           /* line */ (const char *) "v.CC$..CC.v ",
           /* line */ (const char *) "v.C..g..C.v ",
           /* line */ (const char *) "v.CC...CC.v ",
           /* line */ (const char *) "v.CCCCCCCCv ",
           /* line */ (const char *) "v.....MCCCv ",
           /* line */ (const char *) "vvvv.CCC.vv ",
           /* line */ (const char *) "   v....Ev  ",
           /* line */ (const char *) "   vvvvvvv  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "vvvvv.vvvvv",
           /* line */ (const char *) "v$..v.v$..v",
           /* line */ (const char *) "vCCCv.vCCCv",
           /* line */ (const char *) "v...v.v..mv",
           /* line */ (const char *) "v.m.v.v.$.v",
           /* line */ (const char *) "v...v~v...v",
           /* line */ (const char *) "vCCCv.+..Cv",
           /* line */ (const char *) "v...s.vsvvv",
           /* line */ (const char *) "v.E.v.v..$v",
           /* line */ (const char *) "vvvvv.vvvvv",
           /* line */ (const char *) "     ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^ ^    ",
           /* line */ (const char *) "  vv.v.vv  ",
           /* line */ (const char *) "  vB.$.Bv  ",
           /* line */ (const char *) "  vB.$.Bv  ",
           /* line */ (const char *) "  vv.C.vv  ",
           /* line */ (const char *) " vvv.C.vvv ",
           /* line */ (const char *) "^..C.C.C..^",
           /* line */ (const char *) " vvv.C.vvv ",
           /* line */ (const char *) "  vvmC.vv  ",
           /* line */ (const char *) "  vB...Bv  ",
           /* line */ (const char *) "  v..E..v  ",
           /* line */ (const char *) "  vvvvvvv  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvv ",
           /* line */ (const char *) " vBvBvBv$v ",
           /* line */ (const char *) " v.......v ",
           /* line */ (const char *) " v...C...v ",
           /* line */ (const char *) " v..C.C..v ",
           /* line */ (const char *) "^.G.CEC.t.^",
           /* line */ (const char *) " v..C.C..v ",
           /* line */ (const char *) " v...C...v ",
           /* line */ (const char *) " v.......v ",
           /* line */ (const char *) " vvBvBvBvv ",
           /* line */ (const char *) " vvvvvvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvv ",
           /* line */ (const char *) " vgvBvBvgv ",
           /* line */ (const char *) " v.......v ",
           /* line */ (const char *) " v...C...v ",
           /* line */ (const char *) " v..C.C..v ",
           /* line */ (const char *) "^...CEC...^",
           /* line */ (const char *) " v..C.C..v ",
           /* line */ (const char *) " v...C...v ",
           /* line */ (const char *) " v.......v ",
           /* line */ (const char *) " vvBvgvBvv ",
           /* line */ (const char *) " vvvvvvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvvvvvv ",
           /* line */ (const char *) "    vBvBvBv$v ",
           /* line */ (const char *) " vvvv.......v ",
           /* line */ (const char *) " v$.t...C...v ",
           /* line */ (const char *) " vvvv..C.C..v ",
           /* line */ (const char *) "^....g.CEC...^",
           /* line */ (const char *) " vvvv..C.C..v ",
           /* line */ (const char *) " v..v...C...v ",
           /* line */ (const char *) " v..s.......v ",
           /* line */ (const char *) " v$.vvBvBvBvv ",
           /* line */ (const char *) " vvvvvvvvvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvvvv ",
           /* line */ (const char *) " v.CCCCC...v ",
           /* line */ (const char *) " v.C..CCCCCv ",
           /* line */ (const char *) " v.CCCC..C.v ",
           /* line */ (const char *) " v...CC.$CCv ",
           /* line */ (const char *) "^...CCCCCC.v ",
           /* line */ (const char *) " v...C.E.CCv ",
           /* line */ (const char *) " v...C...C.v ",
           /* line */ (const char *) " vg.CCCCCC..^",
           /* line */ (const char *) " vvvvvvvvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^  ",
           /* line */ (const char *) "vvvvvvvvv.v ",
           /* line */ (const char *) "v.....C...v ",
           /* line */ (const char *) "v.$..CC...v ",
           /* line */ (const char *) "v...CCC.m.v ",
           /* line */ (const char *) "v..CC.C...v ",
           /* line */ (const char *) "vCCCCCCCCCv ",
           /* line */ (const char *) "v....C.....^",
           /* line */ (const char *) "v...CC.m..v ",
           /* line */ (const char *) "v.CCCCCCCCv ",
           /* line */ (const char *) "v....CC...v ",
           /* line */ (const char *) "vE...C...$v ",
           /* line */ (const char *) "vvvvvvvvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "vvvvv.vvvvv",
           /* line */ (const char *) "vm....v..gv",
           /* line */ (const char *) "v..$.Cv...v",
           /* line */ (const char *) "vB..CCv...v",
           /* line */ (const char *) "vCCCC....Cv",
           /* line */ (const char *) "vCCCCCCCC.v",
           /* line */ (const char *) "vCCCCCCC..v",
           /* line */ (const char *) "vg...C....v",
           /* line */ (const char *) "vv.vvvv..Ev",
           /* line */ (const char *) " v.v  vvvvv",
           /* line */ (const char *) "  ^        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^     ",
           /* line */ (const char *) " vvvvvv.vvvv ",
           /* line */ (const char *) " v..s.L.s.$v ",
           /* line */ (const char *) " vm.v.L.v..v ",
           /* line */ (const char *) " vvvv.L.vvvv ",
           /* line */ (const char *) "^.....L.....^",
           /* line */ (const char *) " vvvv.L.vvvv ",
           /* line */ (const char *) " v..v.L.vv$v ",
           /* line */ (const char *) " v....Lmvv.v ",
           /* line */ (const char *) " v..vvsvvv.v ",
           /* line */ (const char *) " vE.v......v ",
           /* line */ (const char *) " vvvvvvvvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvvv",
           /* line */ (const char *) " v.LLLL.L.v",
           /* line */ (const char *) " v.LLLL...v",
           /* line */ (const char *) " v.LLLLLL.v",
           /* line */ (const char *) "^..LL$LLL.v",
           /* line */ (const char *) " v........v",
           /* line */ (const char *) " v.LLLLLL.v",
           /* line */ (const char *) " v.LLELLL.v",
           /* line */ (const char *) " v.LLLLLL.v",
           /* line */ (const char *) " v...m....v",
           /* line */ (const char *) " vvvvvvvv.v",
           /* line */ (const char *) "         ^ ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  vvvvvvv  ",
           /* line */ (const char *) "  vLm..Lv  ",
           /* line */ (const char *) "  vL.C.Lv  ",
           /* line */ (const char *) " vvL.C.Lvv ",
           /* line */ (const char *) "^..L.C...t^",
           /* line */ (const char *) " vvL.C.Lvv ",
           /* line */ (const char *) " vvL.C.Lv  ",
           /* line */ (const char *) " vEL$..Lv  ",
           /* line */ (const char *) " vvLLLLLv  ",
           /* line */ (const char *) " vvvvvvvv  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvvv ",
           /* line */ (const char *) " v.CCCC.C.v ",
           /* line */ (const char *) " v.CCCC....^",
           /* line */ (const char *) " v.CCCCCC.v ",
           /* line */ (const char *) "^..CC$.CC.v ",
           /* line */ (const char *) " v.CC$.CC.v ",
           /* line */ (const char *) " v.CCCCCC.v ",
           /* line */ (const char *) " v...CCCC.v ",
           /* line */ (const char *) " v.C.CCCC.v ",
           /* line */ (const char *) " v$..m...Ev ",
           /* line */ (const char *) " vvvvvvvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^  ",
           /* line */ (const char *) " vvvvvvvvv.v ",
           /* line */ (const char *) " v.CCCCC....^",
           /* line */ (const char *) " v.C..CC.CCv ",
           /* line */ (const char *) " v.CCCC$.C.v ",
           /* line */ (const char *) " v...CCvvvvv ",
           /* line */ (const char *) "^...CCCv     ",
           /* line */ (const char *) " v....$vvvv  ",
           /* line */ (const char *) " v...C...Cv  ",
           /* line */ (const char *) " vg.CCCCCCv  ",
           /* line */ (const char *) " vvvvvEvvvv  ",
           /* line */ (const char *) "     vvv     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^          ",
           /* line */ (const char *) "v.vvvvvvvvv ",
           /* line */ (const char *) "v.....C.$.v ",
           /* line */ (const char *) "v.E..CC....^",
           /* line */ (const char *) "v...C.C.m.v ",
           /* line */ (const char *) "vvvvv.....v ",
           /* line */ (const char *) "    vCCCCCv ",
           /* line */ (const char *) "vvvvvC....v ",
           /* line */ (const char *) "v....C.m..v ",
           /* line */ (const char *) "v.CCCCCCC.v ",
           /* line */ (const char *) "v....$....v ",
           /* line */ (const char *) "vvvvvvvvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^     ",
           /* line */ (const char *) " vvvvv.vvvvv",
           /* line */ (const char *) " vm....vv.$v",
           /* line */ (const char *) " v....CvvLLv",
           /* line */ (const char *) "^....CCvv..v",
           /* line */ (const char *) " vCC.C.....v",
           /* line */ (const char *) " vCC.CCCCC.v",
           /* line */ (const char *) " vCC.CCCC..v",
           /* line */ (const char *) " vg.......$v",
           /* line */ (const char *) " vvvvvvEvvvv",
           /* line */ (const char *) "      vvv   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     vvv     ",
           /* line */ (const char *) "   vvvEvvv   ",
           /* line */ (const char *) " vvvCCCCCvvv ",
           /* line */ (const char *) " vCCC...CCCv ",
           /* line */ (const char *) "^...B..$....^",
           /* line */ (const char *) " vCCC...C$Cv ",
           /* line */ (const char *) " vvvCCCCCvvv ",
           /* line */ (const char *) "   vvv.vvv   ",
           /* line */ (const char *) "      ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  vvvvvvvvvv  ",
           /* line */ (const char *) "  v.$.m..$Ev  ",
           /* line */ (const char *) " vvvvv..vvvvv ",
           /* line */ (const char *) " vBCCCCCCCCBv ",
           /* line */ (const char *) "^.==========.^",
           /* line */ (const char *) " vBCCCCCCCCBv ",
           /* line */ (const char *) " vvvvv.vvvvvv ",
           /* line */ (const char *) "      ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvv    ",
           /* line */ (const char *) " v$....Mv    ",
           /* line */ (const char *) " v.CCC=Cv    ",
           /* line */ (const char *) " vCCCC=Cvvvv ",
           /* line */ (const char *) " vCCCC=CCCCv ",
           /* line */ (const char *) "^.....=.....^",
           /* line */ (const char *) " vCCCCCCCCCv ",
           /* line */ (const char *) " vvvvvvv..gv ",
           /* line */ (const char *) "     v$...vv ",
           /* line */ (const char *) "     vEvvvv  ",
           /* line */ (const char *) "     vvv     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " vvv.vvvvvv ",
           /* line */ (const char *) " v$v......v ",
           /* line */ (const char *) " v.v.......^",
           /* line */ (const char *) " v.v...M..v ",
           /* line */ (const char *) " v.v......v ",
           /* line */ (const char *) " vsv...CCCv ",
           /* line */ (const char *) "^......C..v ",
           /* line */ (const char *) " v.....C.Ev ",
           /* line */ (const char *) " vvvvv.vvvv ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " vvv.vvvvvv ",
           /* line */ (const char *) " vvB.BvgEgv ",
           /* line */ (const char *) " vvv.vv...v ",
           /* line */ (const char *) " vvB.Bv...v ",
           /* line */ (const char *) " vvv.vv...v ",
           /* line */ (const char *) " vvB.Bv.M.v ",
           /* line */ (const char *) "^.........v ",
           /* line */ (const char *) " vvBvB.Bvvv ",
           /* line */ (const char *) " vvvvv.vvvv ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^         ",
           /* line */ (const char *) "  vv.vvvvvvvvv",
           /* line */ (const char *) "  vB.BvgEgs..v",
           /* line */ (const char *) "  vv.vv...v..v",
           /* line */ (const char *) "  vB.Bv...vCCv",
           /* line */ (const char *) "  vv.vv...v..v",
           /* line */ (const char *) " vvB.Bv.M.v..v",
           /* line */ (const char *) "^.........v..v",
           /* line */ (const char *) " vvBvB.Bvvv.$v",
           /* line */ (const char *) "  vvvv.vvvvvvv",
           /* line */ (const char *) "      ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^         ",
           /* line */ (const char *) "  vv.vvvvvvvvv",
           /* line */ (const char *) "  vC.CvgEgs..v",
           /* line */ (const char *) "  vC.Cv...v..v",
           /* line */ (const char *) "  vC.Cv...vCCv",
           /* line */ (const char *) "  vC.Cv.M.v..v",
           /* line */ (const char *) " vCC.Cv...v..v",
           /* line */ (const char *) "^.........v..v",
           /* line */ (const char *) " vCCCC.CCCv.$v",
           /* line */ (const char *) " vvvvv.vvvvvvv",
           /* line */ (const char *) "      ^       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " vvv.vvvvvv ",
           /* line */ (const char *) " v........v ",
           /* line */ (const char *) " v.vvvvvv..^",
           /* line */ (const char *) " v.v.vv.v.v ",
           /* line */ (const char *) " v.v.EB.v.v ",
           /* line */ (const char *) " v.v....v.v ",
           /* line */ (const char *) "^..v+vvvv.v ",
           /* line */ (const char *) " v.......$v ",
           /* line */ (const char *) " vvvvv.vvvv ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " vvv.vvvvvv ",
           /* line */ (const char *) " v........v ",
           /* line */ (const char *) " v....C....^",
           /* line */ (const char *) " v...CCC..v ",
           /* line */ (const char *) " v..CCECC.v ",
           /* line */ (const char *) " vB..CCC..v ",
           /* line */ (const char *) "^.....C.CCv ",
           /* line */ (const char *) " vB.....C$v ",
           /* line */ (const char *) " vvvvv.vvvv ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " vvv.vvvvvv ",
           /* line */ (const char *) " v........v ",
           /* line */ (const char *) " v..B.B.B..^",
           /* line */ (const char *) " v..vvvvvvv ",
           /* line */ (const char *) " v..vE.M.Tv ",
           /* line */ (const char *) " v..v$....v ",
           /* line */ (const char *) "^...vvvvv+v ",
           /* line */ (const char *) " v........v ",
           /* line */ (const char *) " vvvvv.vvvv ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " vvv.vvvvvv ",
           /* line */ (const char *) " v$v.v....v ",
           /* line */ (const char *) " v.v.v....v ",
           /* line */ (const char *) " v.t.v..M.v ",
           /* line */ (const char *) " vvv.v....v ",
           /* line */ (const char *) " v.........^",
           /* line */ (const char *) " v.vvvvvvvv ",
           /* line */ (const char *) " v.v....C.v ",
           /* line */ (const char *) " v.vE...v.v ",
           /* line */ (const char *) "^..vvvvvv.v ",
           /* line */ (const char *) " v........v ",
           /* line */ (const char *) " vvvvv.vvvv ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);
}
