//
// Copyright goblinhack@gmail.com
//

#include "my_callstack.hpp"
#include "my_level.hpp"
#include "my_types.hpp"

//
// Create all prefab rooms
//
void rooms_prefab_locked(Gamep g)
{
  TRACE();

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ",
           /* line */ (const char *) " vvvvvv ",
           /* line */ (const char *) " v....+^",
           /* line */ (const char *) " v$...v ",
           /* line */ (const char *) " vvvvvv ",
           /* line */ (const char *) "        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   vvvvvv   ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) " vvv....vvv ",
           /* line */ (const char *) " v$s......v ",
           /* line */ (const char *) " vvv....vvv ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vvv.vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ",
           /* line */ (const char *) "   vvvvvv   ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vB..Bv   ",
           /* line */ (const char *) " vvv....vvv ",
           /* line */ (const char *) " v.s....+$v ",
           /* line */ (const char *) " vvvB..Bvvv ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vB..Bv   ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vB..Bv   ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vvv.vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   vvvvvvv   ",
           /* line */ (const char *) "   v$$...v   ",
           /* line */ (const char *) "   vvvvv+v   ",
           /* line */ (const char *) "   vB...Bv   ",
           /* line */ (const char *) " vvv.....vvv ",
           /* line */ (const char *) " v.........v ",
           /* line */ (const char *) " vvvB...Bvvv ",
           /* line */ (const char *) "   v.....v   ",
           /* line */ (const char *) "   vB...Bv   ",
           /* line */ (const char *) "   v.....v   ",
           /* line */ (const char *) "   vB...Bv   ",
           /* line */ (const char *) "   v.....v   ",
           /* line */ (const char *) "   vvv.vvv   ",
           /* line */ (const char *) "      ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ",
           /* line */ (const char *) "   vvvvvv   ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vB..Bv   ",
           /* line */ (const char *) " vvv....vvv ",
           /* line */ (const char *) " v$s....+$v ",
           /* line */ (const char *) " vvvB..Bvvv ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vB..Bv   ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vB..Bv   ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vvv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ",
           /* line */ (const char *) "   vvvvvvvvv",
           /* line */ (const char *) "   v....+$$v",
           /* line */ (const char *) "   vB..Bvvvv",
           /* line */ (const char *) " vvv....vvv ",
           /* line */ (const char *) " v...M....v ",
           /* line */ (const char *) " vvvB..Bvvv ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vB..Bv   ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vB..Bv   ",
           /* line */ (const char *) "   v$..$v   ",
           /* line */ (const char *) "   vv+vvv   ",
           /* line */ (const char *) "     ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ",
           /* line */ (const char *) "   vvvvvvvvv",
           /* line */ (const char *) "   v....+.bv",
           /* line */ (const char *) "   v....vb$v",
           /* line */ (const char *) "   v....vvvv",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vB..Bv   ",
           /* line */ (const char *) "vvvv....vvvv",
           /* line */ (const char *) "v..........v",
           /* line */ (const char *) "v..........v",
           /* line */ (const char *) "vvvvB..Bvvvv",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vB..Bv   ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vB..Bv   ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vv+vvv   ",
           /* line */ (const char *) "     ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ",
           /* line */ (const char *) "   vvvvvv   ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vB..Bv   ",
           /* line */ (const char *) "vvvv....vvvv",
           /* line */ (const char *) "v$$s.......v",
           /* line */ (const char *) "v$$v.......v",
           /* line */ (const char *) "vvvvB..Bvvvv",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vB..Bv   ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vB..Bv   ",
           /* line */ (const char *) "   v....v   ",
           /* line */ (const char *) "   vv+vvv   ",
           /* line */ (const char *) "     ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ",
           /* line */ (const char *) "   vvvvvv    ",
           /* line */ (const char *) "   v....+...^",
           /* line */ (const char *) "   vB..Bv    ",
           /* line */ (const char *) "vvvv....vvvv ",
           /* line */ (const char *) "v$.C....CM.v ",
           /* line */ (const char *) "v$.C....C..v ",
           /* line */ (const char *) "vvvvvvvvvvvv ",
           /* line */ (const char *) "             ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "             ",
           /* line */ (const char *) "   vvvvvv    ",
           /* line */ (const char *) "   v....+...^",
           /* line */ (const char *) "   vB..Bv    ",
           /* line */ (const char *) "vvvv....vvvv ",
           /* line */ (const char *) "v..CCCCCC..v ",
           /* line */ (const char *) "v..C....CM.v ",
           /* line */ (const char *) "v..C....C..v ",
           /* line */ (const char *) "v$.C....C..v ",
           /* line */ (const char *) "v$.CCCCCC..v ",
           /* line */ (const char *) "vvvvvvvvvvvv ",
           /* line */ (const char *) "             ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ",
           /* line */ (const char *) " vvvvvv ",
           /* line */ (const char *) " v....+^",
           /* line */ (const char *) " v$..$v ",
           /* line */ (const char *) " vvvvvv ",
           /* line */ (const char *) "        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ",
           /* line */ (const char *) " vvvvvv ",
           /* line */ (const char *) " v$`..+^",
           /* line */ (const char *) " v$``.v ",
           /* line */ (const char *) " vvvvvv ",
           /* line */ (const char *) "        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ",
           /* line */ (const char *) "vvvvvvv ",
           /* line */ (const char *) "v.s...+^",
           /* line */ (const char *) "v.v...v ",
           /* line */ (const char *) "v.vvvvv ",
           /* line */ (const char *) "v.`$$$v ",
           /* line */ (const char *) "vvvvvvv ",
           /* line */ (const char *) "        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ",
           /* line */ (const char *) " vvvvvv ",
           /* line */ (const char *) " v....+^",
           /* line */ (const char *) " v....v ",
           /* line */ (const char *) " v$...v ",
           /* line */ (const char *) " vvvvvv ",
           /* line */ (const char *) "        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ",
           /* line */ (const char *) " vvvvvv ",
           /* line */ (const char *) " v....+^",
           /* line */ (const char *) " v..m.v ",
           /* line */ (const char *) " v....v ",
           /* line */ (const char *) " v$...v ",
           /* line */ (const char *) " vvvvvv ",
           /* line */ (const char *) "        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ",
           /* line */ (const char *) " vvvvvv ",
           /* line */ (const char *) " v....+^",
           /* line */ (const char *) " v....v ",
           /* line */ (const char *) " v....v ",
           /* line */ (const char *) " v....v ",
           /* line */ (const char *) " v$..Mv ",
           /* line */ (const char *) " vvvvvv ",
           /* line */ (const char *) "        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ",
           /* line */ (const char *) " vvvvvv ",
           /* line */ (const char *) " vM...v ",
           /* line */ (const char *) " v.$..v ",
           /* line */ (const char *) " v..$.+^",
           /* line */ (const char *) " vm...v ",
           /* line */ (const char *) " vvvvvv ",
           /* line */ (const char *) "        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "           ",
           /* line */ (const char *) " vvvvvv    ",
           /* line */ (const char *) " v....vvvv ",
           /* line */ (const char *) " v.$.....v ",
           /* line */ (const char *) " v..$....+^",
           /* line */ (const char *) " vM......v ",
           /* line */ (const char *) " vvvvvvvvv ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ",
           /* line */ (const char *) " vvvvvv     ",
           /* line */ (const char *) " v....v     ",
           /* line */ (const char *) " v.$..vvvv  ",
           /* line */ (const char *) " v..$....+.^",
           /* line */ (const char *) " vM......v  ",
           /* line */ (const char *) " vvvvvvvvv  ",
           /* line */ (const char *) "            ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "            ",
           /* line */ (const char *) " vvvvvv     ",
           /* line */ (const char *) " v....v     ",
           /* line */ (const char *) " v.$..vvvv  ",
           /* line */ (const char *) " v..$....+.^",
           /* line */ (const char *) " vG...vvvv  ",
           /* line */ (const char *) " v....v     ",
           /* line */ (const char *) " vvvvvv     ",
           /* line */ (const char *) "            ",
           /* line */ (const char *) "            ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "               ",
           /* line */ (const char *) " vvvvvv        ",
           /* line */ (const char *) " v....v        ",
           /* line */ (const char *) " v.$..vvvvvvvv ",
           /* line */ (const char *) " v..$........+^",
           /* line */ (const char *) " vG...vvvvvvvv ",
           /* line */ (const char *) " v....v        ",
           /* line */ (const char *) " vvvvvv        ",
           /* line */ (const char *) "               ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "               ",
           /* line */ (const char *) " vvvvvv        ",
           /* line */ (const char *) " v....v        ",
           /* line */ (const char *) " v.$..vvvvvvvv ",
           /* line */ (const char *) " v..$....CC..+^",
           /* line */ (const char *) " vM...vvvvvvvv ",
           /* line */ (const char *) " v....v        ",
           /* line */ (const char *) " v....v        ",
           /* line */ (const char *) " v....v        ",
           /* line */ (const char *) " vvvvvv        ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS | ROOM_FLAG_LOCKED, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^    ",
           /* line */ (const char *) "^......... ",
           /* line */ (const char *) " .vvvvvvv.^",
           /* line */ (const char *) " .+.B.B.v. ",
           /* line */ (const char *) " .v..$..v. ",
           /* line */ (const char *) " .v.B.B.v. ",
           /* line */ (const char *) " .vvvvvvv. ",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) "        ^  ",
           /* end */ nullptr);
}
