//
// Copyright goblinhack@gmail.com
//

#include "my_callstack.hpp"
#include "my_level.hpp"

//
// Create all start rooms
//
void rooms_start(Gamep g)
{
  TRACE();

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) " xB.....Bx ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) "^........x ",
           /* line */ (const char *) " x...@...x ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x........^",
           /* line */ (const char *) " xB......x ",
           /* line */ (const char *) " xxxxxx.xx ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) " xB.....Bx ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) "^..CCCCC.x ",
           /* line */ (const char *) " xxx...xxx ",
           /* line */ (const char *) " xx.....xx ",
           /* line */ (const char *) " xx..@..xx ",
           /* line */ (const char *) " xx.....xx ",
           /* line */ (const char *) " xxx...xxx ",
           /* line */ (const char *) " x.CCCCC.x ",
           /* line */ (const char *) " x........^",
           /* line */ (const char *) " xB......x ",
           /* line */ (const char *) " xxxxxx.xx ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) "^.....xxxx ",
           /* line */ (const char *) " xxx...xxx ",
           /* line */ (const char *) " xx.....xx ",
           /* line */ (const char *) " xx..@..xx ",
           /* line */ (const char *) " xx.....xx ",
           /* line */ (const char *) " xxx.....x ",
           /* line */ (const char *) " xxxx.....^",
           /* line */ (const char *) " xxxxxx.xx ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x.x.x.x.x ",
           /* line */ (const char *) "^..x.x...x ",
           /* line */ (const char *) " x.xxx.x.x ",
           /* line */ (const char *) " x.x@x.x.x ",
           /* line */ (const char *) " x.x.x.x..^",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " xxxxxx.xx ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) " x...C...x ",
           /* line */ (const char *) " x.xxxxx.x ",
           /* line */ (const char *) "^..x...x.x ",
           /* line */ (const char *) " xCx...x.x ",
           /* line */ (const char *) " x.x@..xCx ",
           /* line */ (const char *) " x.xxx.x..^",
           /* line */ (const char *) " x...C...x ",
           /* line */ (const char *) " xxxxxx.xx ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x.CCCCC.x ",
           /* line */ (const char *) "^..CC@CC.x ",
           /* line */ (const char *) " x.CC.CC.x ",
           /* line */ (const char *) " x.CC.CC.x ",
           /* line */ (const char *) " x.CC.CC.x ",
           /* line */ (const char *) " x.CC.CC..^",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " xxxxxx.xx ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x.CCCCC.x ",
           /* line */ (const char *) "^..C...C.x ",
           /* line */ (const char *) " x.C.@.C.x ",
           /* line */ (const char *) " x.C...C.x ",
           /* line */ (const char *) " x.CC.CC.x ",
           /* line */ (const char *) " x.CC.CC.x ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x.CC.CC.x ",
           /* line */ (const char *) " x.CC.CC..^",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " xxxxxx.xx ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x.CCCCC.x ",
           /* line */ (const char *) " x.C...C.x ",
           /* line */ (const char *) "^..C.@.C.x ",
           /* line */ (const char *) " x.C...C.x ",
           /* line */ (const char *) " x.CC.CC.x ",
           /* line */ (const char *) " x.CC.CC.x ",
           /* line */ (const char *) " x.CC.CC.x ",
           /* line */ (const char *) " x.CC.CC..^",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " xxxxxx.xx ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^         ",
           /* line */ (const char *) " xxx.xxxxxxxx ",
           /* line */ (const char *) " x..........x ",
           /* line */ (const char *) " x.CCCCCCCC.x ",
           /* line */ (const char *) " x.CCC....C.x ",
           /* line */ (const char *) "^..CC..@..C.x ",
           /* line */ (const char *) " x.C......C.x ",
           /* line */ (const char *) " x.CC....CC.x ",
           /* line */ (const char *) " x.CCC..CCC.x ",
           /* line */ (const char *) " x.CCC.CCCC.x ",
           /* line */ (const char *) " x.CCC.CCCC..^",
           /* line */ (const char *) " x..........x ",
           /* line */ (const char *) " xxxxxx.xx.xx ",
           /* line */ (const char *) "       ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x.CCCCC.x ",
           /* line */ (const char *) "^..CC@CC.x ",
           /* line */ (const char *) " x.CC.CC.x ",
           /* line */ (const char *) " x.CC.CC.x ",
           /* line */ (const char *) " x.CC.CC.x ",
           /* line */ (const char *) " x.CC.CC..^",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " xxxxxx.xx ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x.LLLLL.x ",
           /* line */ (const char *) "^..L...L.x ",
           /* line */ (const char *) " x.L.@.L.x ",
           /* line */ (const char *) " x.L...L.x ",
           /* line */ (const char *) " x.LL.LL.x ",
           /* line */ (const char *) " x.LL.LL.x ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x.LL.LL.x ",
           /* line */ (const char *) " x.LL.LL..^",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " xxxxxx.xx ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x.LL.LL.x ",
           /* line */ (const char *) " x.LL.LL.x ",
           /* line */ (const char *) " x...@...x ",
           /* line */ (const char *) " x.LL.LL.x ",
           /* line */ (const char *) " x.LL.LL..^",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " xxxxxx.xx ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) "^........x ",
           /* line */ (const char *) " x.LL.LL.x ",
           /* line */ (const char *) " x.LL.LL.x ",
           /* line */ (const char *) " x...@...x ",
           /* line */ (const char *) " x.LL.LL.x ",
           /* line */ (const char *) " x.LL.LL..^",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x.LL.LL.x ",
           /* line */ (const char *) " x.LL.LL.x ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " xxxxxx.xx ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x.LLLLL.x ",
           /* line */ (const char *) " x.L...L.x ",
           /* line */ (const char *) "^..L.@.L.x ",
           /* line */ (const char *) " x.L...L.x ",
           /* line */ (const char *) " x.LL.LL.x ",
           /* line */ (const char *) " x.LL.LL.x ",
           /* line */ (const char *) " x.LL.LL.x ",
           /* line */ (const char *) " x.LL.LL..^",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " xxxxxx.xx ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^         ",
           /* line */ (const char *) " xxx.xxxxxxxx ",
           /* line */ (const char *) " x..........x ",
           /* line */ (const char *) " x.~~~~~~~~.x ",
           /* line */ (const char *) " x.~~~....~.x ",
           /* line */ (const char *) "^..~~..@..~.x ",
           /* line */ (const char *) " x.~......~.x ",
           /* line */ (const char *) " x.~~....~~.x ",
           /* line */ (const char *) " x.~~~..~~~.x ",
           /* line */ (const char *) " x.~~~.~~~~.x ",
           /* line */ (const char *) " x.~~~.~~~~..^",
           /* line */ (const char *) " x..........x ",
           /* line */ (const char *) " xxxxxx.xx.xx ",
           /* line */ (const char *) "       ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^     ",
           /* line */ (const char *) "     x...x   ",
           /* line */ (const char *) "  xxxx.xxxx  ",
           /* line */ (const char *) " xxB.....Bx  ",
           /* line */ (const char *) " xx.......x  ",
           /* line */ (const char *) "^.........x  ",
           /* line */ (const char *) " xx...@...xx ",
           /* line */ (const char *) " xx.......xx ",
           /* line */ (const char *) "  x.........^",
           /* line */ (const char *) "  xB.....Bxx ",
           /* line */ (const char *) "  xxxx.xxxxx ",
           /* line */ (const char *) "    x...x    ",
           /* line */ (const char *) "      ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^     ",
           /* line */ (const char *) "     x...x   ",
           /* line */ (const char *) "  xxxx.xxxx  ",
           /* line */ (const char *) " xx|.....|x  ",
           /* line */ (const char *) " Cx.......x  ",
           /* line */ (const char *) "^.........x  ",
           /* line */ (const char *) " Cx...@...xx ",
           /* line */ (const char *) " xx.......xC ",
           /* line */ (const char *) "  x.........^",
           /* line */ (const char *) "  x|.....|xC ",
           /* line */ (const char *) "  xxxx.xxxxx ",
           /* line */ (const char *) "    x...x    ",
           /* line */ (const char *) "      ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^     ",
           /* line */ (const char *) "     x...x   ",
           /* line */ (const char *) "  xxxx.xxxx  ",
           /* line */ (const char *) " xx.......x  ",
           /* line */ (const char *) " Cx.xx..x.x  ",
           /* line */ (const char *) "^.........x  ",
           /* line */ (const char *) " Cx...@...xx ",
           /* line */ (const char *) " xx.x.....xC ",
           /* line */ (const char *) "  x.xx..x...^",
           /* line */ (const char *) "  x.......xC ",
           /* line */ (const char *) "  xxxx.xxxxx ",
           /* line */ (const char *) "    x...x    ",
           /* line */ (const char *) "      ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^     ",
           /* line */ (const char *) "        x.x     ",
           /* line */ (const char *) "        x.x     ",
           /* line */ (const char *) "        x.x     ",
           /* line */ (const char *) " xxxxxxxx.xxxx  ",
           /* line */ (const char *) "^...........Bx  ",
           /* line */ (const char *) " xxxxx...@...x  ",
           /* line */ (const char *) "     xB......xx ",
           /* line */ (const char *) "     xxxx......^",
           /* line */ (const char *) "        x.xxxxx ",
           /* line */ (const char *) "        x.x     ",
           /* line */ (const char *) "        x.x     ",
           /* line */ (const char *) "         ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^     ",
           /* line */ (const char *) " xxxx   x.x     ",
           /* line */ (const char *) " x$.x   x.x     ",
           /* line */ (const char *) " x..xxxxx.x     ",
           /* line */ (const char *) " x..s...C.x     ",
           /* line */ (const char *) " xxxxxxxx.x     ",
           /* line */ (const char *) "        x.x     ",
           /* line */ (const char *) " xxxxxxxx.xxxx  ",
           /* line */ (const char *) "^...........Bx  ",
           /* line */ (const char *) " xxxxx...@...x  ",
           /* line */ (const char *) "     xB......xx ",
           /* line */ (const char *) "     xxxx......^",
           /* line */ (const char *) "        x.xxxxx ",
           /* line */ (const char *) "        x.x     ",
           /* line */ (const char *) "        x.x     ",
           /* line */ (const char *) "         ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "          ^     ",
           /* line */ (const char *) " xxxx   x.x     ",
           /* line */ (const char *) " x$.x   x.x     ",
           /* line */ (const char *) " x..xxxxx.x     ",
           /* line */ (const char *) " x..s````.x     ",
           /* line */ (const char *) " x..xxxxx.x     ",
           /* line */ (const char *) " x..x   x.x     ",
           /* line */ (const char *) " xxxxxxxx.xxxx  ",
           /* line */ (const char *) "^...........Bx  ",
           /* line */ (const char *) " xxxxx...@...x  ",
           /* line */ (const char *) "     xB......xx ",
           /* line */ (const char *) "     xxxx......^",
           /* line */ (const char *) "        x.xxxxx ",
           /* line */ (const char *) "        x.x     ",
           /* line */ (const char *) "        x.x     ",
           /* line */ (const char *) "         ^      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) " x``....Bx ",
           /* line */ (const char *) " x`......x ",
           /* line */ (const char *) "^........x ",
           /* line */ (const char *) " x...@...x ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x........^",
           /* line */ (const char *) " xB......x ",
           /* line */ (const char *) " xxxxxxxxx ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) " x...```$x ",
           /* line */ (const char *) " x....```x ",
           /* line */ (const char *) "^......``x ",
           /* line */ (const char *) " x......`x ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x...@...x ",
           /* line */ (const char *) " xB.....Bx ",
           /* line */ (const char *) " xxxxxxxxx ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^         ",
           /* line */ (const char *) " xxx.xxxxxxxx ",
           /* line */ (const char *) " x...````s.mx ",
           /* line */ (const char *) " x....```x.`x ",
           /* line */ (const char *) "^......``x``x ",
           /* line */ (const char *) " x......`xxsx ",
           /* line */ (const char *) " x........x.x ",
           /* line */ (const char *) " x........x$x ",
           /* line */ (const char *) " x........xxx ",
           /* line */ (const char *) " x...........^",
           /* line */ (const char *) " x...@......x ",
           /* line */ (const char *) " xB.........x ",
           /* line */ (const char *) " xxxxxxxxxxxx ",
           /* line */ (const char *) "              ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^            ",
           /* line */ (const char *) " xxx.xxxxxxxxxxx ",
           /* line */ (const char *) " x...````s.m...x ",
           /* line */ (const char *) " x....```x....`x ",
           /* line */ (const char *) "^......``x...``x ",
           /* line */ (const char *) " x......`xxxxxsx ",
           /* line */ (const char *) " x........x....x ",
           /* line */ (const char *) " x........x$...x ",
           /* line */ (const char *) " x........xxxxxx ",
           /* line */ (const char *) " x..............^",
           /* line */ (const char *) " x...@.........x ",
           /* line */ (const char *) " xB............x ",
           /* line */ (const char *) " xxxxxxxxxxxxxxx ",
           /* line */ (const char *) "                 ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^            ",
           /* line */ (const char *) " xxx.xxxxxxxxxx  ",
           /* line */ (const char *) " x...```C.C  .x  ",
           /* line */ (const char *) " x....```xxxx.x  ",
           /* line */ (const char *) "^......``xxxx.x  ",
           /* line */ (const char *) " x......`xxxxsxx ",
           /* line */ (const char *) " x........x....x ",
           /* line */ (const char *) " x........x...$x ",
           /* line */ (const char *) " x........xxxxxx ",
           /* line */ (const char *) " x..............^",
           /* line */ (const char *) " x...@.........x ",
           /* line */ (const char *) " xB............x ",
           /* line */ (const char *) " xxxxxxxxxxxxxxx ",
           /* line */ (const char *) "                 ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) "   x.xxxxx ",
           /* line */ (const char *) "   x....Bx ",
           /* line */ (const char *) "   x.....x ",
           /* line */ (const char *) " xxx.....x ",
           /* line */ (const char *) "^........x ",
           /* line */ (const char *) " xB......x ",
           /* line */ (const char *) " x...@....^",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " xxxxxxxxx ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) "   x.xxx   ",
           /* line */ (const char *) "   x.B.x   ",
           /* line */ (const char *) "   x...xxx ",
           /* line */ (const char *) " xxx.....x ",
           /* line */ (const char *) "^........x ",
           /* line */ (const char *) " xB......x ",
           /* line */ (const char *) " x...@....^",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " xxxxxxxxx ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) "   x.xxx   ",
           /* line */ (const char *) "   x.B.x   ",
           /* line */ (const char *) "   x...xxx ",
           /* line */ (const char *) " xxx.....x ",
           /* line */ (const char *) "^........x ",
           /* line */ (const char *) " xB......x ",
           /* line */ (const char *) " x...@....^",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " xxxxxxxxx ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) "   x.xxx   ",
           /* line */ (const char *) "   x.B.x   ",
           /* line */ (const char *) "   x...xxx ",
           /* line */ (const char *) " xxx.....x ",
           /* line */ (const char *) "^........x ",
           /* line */ (const char *) " xB......x ",
           /* line */ (const char *) " xxx.@....^",
           /* line */ (const char *) "   x.....x ",
           /* line */ (const char *) "   xxxxxxx ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) "   x.xxx   ",
           /* line */ (const char *) "   x.B.x   ",
           /* line */ (const char *) "   x...xxx ",
           /* line */ (const char *) " xxx......^",
           /* line */ (const char *) "^........x ",
           /* line */ (const char *) " xB....xxx ",
           /* line */ (const char *) " xxx.@.x   ",
           /* line */ (const char *) "   x...x   ",
           /* line */ (const char *) "   xxxxx   ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxx   ",
           /* line */ (const char *) "^......x   ",
           /* line */ (const char *) " xxxB..xxx ",
           /* line */ (const char *) "   x......^",
           /* line */ (const char *) "   x....Bx ",
           /* line */ (const char *) "   x...xxx ",
           /* line */ (const char *) "   x.@.x   ",
           /* line */ (const char *) "   x...x   ",
           /* line */ (const char *) "   xxxxx   ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) "^.........^",
           /* line */ (const char *) " xxxB.Bxxx ",
           /* line */ (const char *) "   x...x   ",
           /* line */ (const char *) "   x...x   ",
           /* line */ (const char *) "   x...x   ",
           /* line */ (const char *) "   x.@.x   ",
           /* line */ (const char *) "   x...x   ",
           /* line */ (const char *) "   xxxxx   ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) "^.........^",
           /* line */ (const char *) " xxx...xxx ",
           /* line */ (const char *) "   x.@.x   ",
           /* line */ (const char *) "   xB.Bx   ",
           /* line */ (const char *) "   xxxxx   ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) "^.........^",
           /* line */ (const char *) " xxx...xxx ",
           /* line */ (const char *) "   x...x   ",
           /* line */ (const char *) "   x...x   ",
           /* line */ (const char *) "   x...x   ",
           /* line */ (const char *) "   x...x   ",
           /* line */ (const char *) "   x.@.x   ",
           /* line */ (const char *) "   xB.Bx   ",
           /* line */ (const char *) "   xxxxx   ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) "^.........^",
           /* line */ (const char *) " xxx...xxx ",
           /* line */ (const char *) " xmx...x$x ",
           /* line */ (const char *) " x.`CCC`.x ",
           /* line */ (const char *) " xxx...xxx ",
           /* line */ (const char *) "   x...x   ",
           /* line */ (const char *) "   x.@.x   ",
           /* line */ (const char *) "   xB.Bx   ",
           /* line */ (const char *) "   xxxxx   ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) "^.........^",
           /* line */ (const char *) " xxxB.Bxxx ",
           /* line */ (const char *) " xmx...x$x ",
           /* line */ (const char *) " x.x...x.x ",
           /* line */ (const char *) " x.x...x`x ",
           /* line */ (const char *) " x.x...xCx ",
           /* line */ (const char *) " x``CCC``x ",
           /* line */ (const char *) " xxx...xxx ",
           /* line */ (const char *) "   x...x   ",
           /* line */ (const char *) "  xx...xx  ",
           /* line */ (const char *) "  xB.@.Bx  ",
           /* line */ (const char *) "  xx...xx  ",
           /* line */ (const char *) "   xB.Bx   ",
           /* line */ (const char *) "   xxxxx   ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^          ",
           /* line */ (const char *) " xxx.xxxxxxxxxx",
           /* line */ (const char *) "^.............x",
           /* line */ (const char *) " xxxxxxxxxx...x",
           /* line */ (const char *) "          x.@.x",
           /* line */ (const char *) "          xB.Bx",
           /* line */ (const char *) "          xxxxx",
           /* line */ (const char *) "               ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^          ",
           /* line */ (const char *) " xxx.xxxxxxxxxx",
           /* line */ (const char *) "^...........``x",
           /* line */ (const char *) " x`x...xx....`x",
           /* line */ (const char *) " x`xx...x.....x",
           /* line */ (const char *) " x````........x",
           /* line */ (const char *) " xx`xxxxxxx...x",
           /* line */ (const char *) "  xCxB...$x...x",
           /* line */ (const char *) "  x`x.....x...x",
           /* line */ (const char *) "  xCx..m..x.@.x",
           /* line */ (const char *) "  x`x.....x...x",
           /* line */ (const char *) "  x.s....BxB.Bx",
           /* line */ (const char *) "  xxxxxxxxxxxxx",
           /* line */ (const char *) "               ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^           ",
           /* line */ (const char *) "x.xxxxxxxxxx ",
           /* line */ (const char *) "x...........^",
           /* line */ (const char *) "xxxxxxxxB..x ",
           /* line */ (const char *) "       x.@.x ",
           /* line */ (const char *) "       xB..x ",
           /* line */ (const char *) "xxxxxxxx...x ",
           /* line */ (const char *) "x...........^",
           /* line */ (const char *) "x.xxxxxxxxxx ",
           /* line */ (const char *) " ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^           ",
           /* line */ (const char *) "x.xxxxxxxxxx ",
           /* line */ (const char *) "x...........^",
           /* line */ (const char *) "xxxxxxxxB..x ",
           /* line */ (const char *) "       x.@.x ",
           /* line */ (const char *) "       xB..x ",
           /* line */ (const char *) "xxxxxxxx...x ",
           /* line */ (const char *) "x...........^",
           /* line */ (const char *) "x.xxxxxxxxxx ",
           /* line */ (const char *) " ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^           ",
           /* line */ (const char *) "x.xxxxxxxxxx ",
           /* line */ (const char *) "x...........^",
           /* line */ (const char *) "x..........x ",
           /* line */ (const char *) "x.xxxxxxB.Bx ",
           /* line */ (const char *) "x.x    x...x ",
           /* line */ (const char *) "x.x    x.@.x ",
           /* line */ (const char *) "x.x    x...x ",
           /* line */ (const char *) "x.xxxxxxB.Bx ",
           /* line */ (const char *) "x..........x ",
           /* line */ (const char *) "x.x.x.x.x.xx ",
           /* line */ (const char *) "x...........^",
           /* line */ (const char *) "x.xxxxxxxxxx ",
           /* line */ (const char *) " ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^              ",
           /* line */ (const char *) "x.xxxxxxxxxxxxx ",
           /* line */ (const char *) "x..............^",
           /* line */ (const char *) "xx`xxxxxB....Bx ",
           /* line */ (const char *) " xCx...x......x ",
           /* line */ (const char *) " x.s..$x..@...x ",
           /* line */ (const char *) " xCx...x......x ",
           /* line */ (const char *) "xx`xxxxxB....Bx ",
           /* line */ (const char *) "x..............^",
           /* line */ (const char *) "x.xxxxxxxxxxxxx ",
           /* line */ (const char *) " ^              ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^              ",
           /* line */ (const char *) "x.xxxxxxxxxxxxx ",
           /* line */ (const char *) "x..............^",
           /* line */ (const char *) "xx`xxxxxCC..CCx ",
           /* line */ (const char *) " x.s...xC....Cx ",
           /* line */ (const char *) " xCx...x..@...x ",
           /* line */ (const char *) " xCx...x......x ",
           /* line */ (const char *) " x`x...x......x ",
           /* line */ (const char *) " x`x..$xC....Cx ",
           /* line */ (const char *) "xx`xxxxxCCCCCCx ",
           /* line */ (const char *) "x..............^",
           /* line */ (const char *) "x.xxxxxxxxxxxxx ",
           /* line */ (const char *) " ^              ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^           ",
           /* line */ (const char *) "x.xxxxxxxxxx ",
           /* line */ (const char *) "x...........^",
           /* line */ (const char *) "x.xxxxxx...x ",
           /* line */ (const char *) "x.x    x.@.x ",
           /* line */ (const char *) "x.x    x...x ",
           /* line */ (const char *) "x.xxxxxxB.Bx ",
           /* line */ (const char *) "x...........^",
           /* line */ (const char *) "x.xxxxxxxxxx ",
           /* line */ (const char *) " ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^           ",
           /* line */ (const char *) "x.xxxxxxxxxx ",
           /* line */ (const char *) "x...........^",
           /* line */ (const char *) "x.xxxxxx...x ",
           /* line */ (const char *) "x.x    x.@.x ",
           /* line */ (const char *) "x.x    x...x ",
           /* line */ (const char *) "x.xxxxxxB.Bx ",
           /* line */ (const char *) "x..CC......x ",
           /* line */ (const char *) "x...CC.....x ",
           /* line */ (const char *) "x....CC.....^",
           /* line */ (const char *) "x.xxxxxxxxxx ",
           /* line */ (const char *) " ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^           ",
           /* line */ (const char *) "x.xxxxxxxxxx ",
           /* line */ (const char *) "x..CC.....Bx ",
           /* line */ (const char *) "x...CC.....x ",
           /* line */ (const char *) "x....CC....x ",
           /* line */ (const char *) "x.xxxxxx...x ",
           /* line */ (const char *) "x.x    x.@.x ",
           /* line */ (const char *) "x.x    x...x ",
           /* line */ (const char *) "x.xxxxxxB.Bx ",
           /* line */ (const char *) "x..CC......x ",
           /* line */ (const char *) "x...CC.....x ",
           /* line */ (const char *) "x....CC.....^",
           /* line */ (const char *) "x.xxxxxxxxxx ",
           /* line */ (const char *) " ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^           ",
           /* line */ (const char *) "x.xxxxxxxxxx ",
           /* line */ (const char *) "x...........^",
           /* line */ (const char *) "x.xxxxxx...x ",
           /* line */ (const char *) "x.x    x.@.x ",
           /* line */ (const char *) "x.x    x...x ",
           /* line */ (const char *) "x.x    x.B.x ",
           /* line */ (const char *) "x.x    x...x ",
           /* line */ (const char *) "x.xxxxxxxxxx ",
           /* line */ (const char *) "x.s.......$x ",
           /* line */ (const char *) "x.xxxxxxxxxx ",
           /* line */ (const char *) " ^           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^              ",
           /* line */ (const char *) "x.xxxxxxxxxxxxx ",
           /* line */ (const char *) "x..............^",
           /* line */ (const char *) "x.xxxxxx......x ",
           /* line */ (const char *) "x.x    x.@....x ",
           /* line */ (const char *) "x.x    x......x ",
           /* line */ (const char *) "x.x    x`.....x ",
           /* line */ (const char *) "x.x    x``...Bx ",
           /* line */ (const char *) "x.xxxxxxCxxxxxx ",
           /* line */ (const char *) "x.```C```s...$x ",
           /* line */ (const char *) "x.xxxxxxxxxxxxx ",
           /* line */ (const char *) " ^              ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^      ",
           /* line */ (const char *) "  xxx.xxxxx ",
           /* line */ (const char *) "  x.......xx",
           /* line */ (const char *) " xx.B.B.B..x",
           /* line */ (const char *) "^..........x",
           /* line */ (const char *) " xx.B......x",
           /* line */ (const char *) "  x.....@..x",
           /* line */ (const char *) "  x.B......x",
           /* line */ (const char *) "  x.......xx",
           /* line */ (const char *) "  xxxxxxxxxx",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^      ",
           /* line */ (const char *) "  xxx.xxxxx ",
           /* line */ (const char *) "  x.......xx",
           /* line */ (const char *) " xx.`.`.`..x",
           /* line */ (const char *) "^..........x",
           /* line */ (const char *) " xx.`......x",
           /* line */ (const char *) "  x.....@..x",
           /* line */ (const char *) "  x.`......x",
           /* line */ (const char *) "  x.......xx",
           /* line */ (const char *) "  xxxxxxxxxx",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^        ",
           /* line */ (const char *) "x.xxxxxx  ",
           /* line */ (const char *) "x......x  ",
           /* line */ (const char *) "xx.....xx ",
           /* line */ (const char *) " x.B.B..x ",
           /* line */ (const char *) " x......x ",
           /* line */ (const char *) " xx...@..^",
           /* line */ (const char *) "  xx....x ",
           /* line */ (const char *) "  xxxxxxx ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^        ",
           /* line */ (const char *) "x.xxxxxx  ",
           /* line */ (const char *) "x.....mx  ",
           /* line */ (const char *) "xx.....xx ",
           /* line */ (const char *) " x.B.B..x ",
           /* line */ (const char *) " x......x ",
           /* line */ (const char *) " xx....xx ",
           /* line */ (const char *) "  xCCCCx  ",
           /* line */ (const char *) " xx....xx ",
           /* line */ (const char *) " x......x ",
           /* line */ (const char *) " xx...@..^",
           /* line */ (const char *) "  xx....x ",
           /* line */ (const char *) "  xxxxxxx ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    xxxxxxx   ",
           /* line */ (const char *) " xxxx.....xx  ",
           /* line */ (const char *) "^..........xx ",
           /* line */ (const char *) " xxxxxx..B..x ",
           /* line */ (const char *) " xCCCCx|....x ",
           /* line */ (const char *) " xC..Cs..@...^",
           /* line */ (const char *) " xC$.Cx|....x ",
           /* line */ (const char *) " xCCCCxxxxxxx ",
           /* line */ (const char *) " xxxxxx       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    xxxxxxx   ",
           /* line */ (const char *) " xxxx.....xx  ",
           /* line */ (const char *) "^..........xx ",
           /* line */ (const char *) " xxxxxx..B..x ",
           /* line */ (const char *) " xC..Cx|....x ",
           /* line */ (const char *) " x.$m.s..@...^",
           /* line */ (const char *) " xC..Cx|....x ",
           /* line */ (const char *) " xxxxxxxxxxxx ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    xxxxxxx   ",
           /* line */ (const char *) " xxxx.....xx  ",
           /* line */ (const char *) "^.......B..xx ",
           /* line */ (const char *) " xxxxxx.....x ",
           /* line */ (const char *) " x$..Cx|....x ",
           /* line */ (const char *) " x...Cs..@...^",
           /* line */ (const char *) " x...Cx|....x ",
           /* line */ (const char *) " xm..Cxxxxxxx ",
           /* line */ (const char *) " xxxxxx       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  xxxxxxxxx ",
           /* line */ (const char *) " xx.CCCCCCx ",
           /* line */ (const char *) "^....CCCCCx ",
           /* line */ (const char *) " xxC..CCCCx ",
           /* line */ (const char *) "  xCC.....x ",
           /* line */ (const char *) "  xxx...@.x ",
           /* line */ (const char *) "    xB.....^",
           /* line */ (const char *) "    xxxxxxx ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  xxxxxxxxx ",
           /* line */ (const char *) " xx.CCCCCCx ",
           /* line */ (const char *) "^....CCCCCx ",
           /* line */ (const char *) " xxC..CCCCx ",
           /* line */ (const char *) "  xCC...CCx ",
           /* line */ (const char *) "  xCCC...Cx ",
           /* line */ (const char *) "  xCCC...Cx ",
           /* line */ (const char *) "  xCC.....x ",
           /* line */ (const char *) "  xxx...@.x ",
           /* line */ (const char *) "    xB.....^",
           /* line */ (const char *) "    xxxxxxx ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^   ",
           /* line */ (const char *) "     x.x  ",
           /* line */ (const char *) "     x.x  ",
           /* line */ (const char *) "    xx.xx ",
           /* line */ (const char *) "    xB.Bx ",
           /* line */ (const char *) "xxxxx...x ",
           /* line */ (const char *) "xB......x ",
           /* line */ (const char *) "x.......x ",
           /* line */ (const char *) "x.@.....x ",
           /* line */ (const char *) "x........^",
           /* line */ (const char *) "xxxxxxxxx ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^   ",
           /* line */ (const char *) "     x.x  ",
           /* line */ (const char *) "     x.x  ",
           /* line */ (const char *) "    xx.xx ",
           /* line */ (const char *) "    xB.Bx ",
           /* line */ (const char *) "    x...x ",
           /* line */ (const char *) "    x|.|x ",
           /* line */ (const char *) "    x...x ",
           /* line */ (const char *) "xxxxx|.|x ",
           /* line */ (const char *) "xCCCC...x ",
           /* line */ (const char *) "xC.....Cx ",
           /* line */ (const char *) "xC.@...Cx ",
           /* line */ (const char *) "xC.....Cx ",
           /* line */ (const char *) "xCCCCC...^",
           /* line */ (const char *) "xxxxxxxxx ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^   ",
           /* line */ (const char *) "     x.x  ",
           /* line */ (const char *) "     x.x  ",
           /* line */ (const char *) "    xx.xx ",
           /* line */ (const char *) "    xC.Cx ",
           /* line */ (const char *) "    xB.Bx ",
           /* line */ (const char *) "    xC.Cx ",
           /* line */ (const char *) "    x...x ",
           /* line */ (const char *) "xxxxxC.Cx ",
           /* line */ (const char *) "x.......x ",
           /* line */ (const char *) "x.......x ",
           /* line */ (const char *) "x.@.....x ",
           /* line */ (const char *) "x........^",
           /* line */ (const char *) "xxxxxxxxx ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^   ",
           /* line */ (const char *) "     x.x  ",
           /* line */ (const char *) "     x.x  ",
           /* line */ (const char *) "    xx.xx ",
           /* line */ (const char *) "    xB.Bx ",
           /* line */ (const char *) "    x...x ",
           /* line */ (const char *) "xxxxxB.Bx ",
           /* line */ (const char *) "xB......x ",
           /* line */ (const char *) "x.......x ",
           /* line */ (const char *) "x.@.....x ",
           /* line */ (const char *) "x........^",
           /* line */ (const char *) "xxxxxxxxx ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ^         ",
           /* line */ (const char *) "x.xxxxxx   ",
           /* line */ (const char *) "x......x   ",
           /* line */ (const char *) "x.cCCc.x   ",
           /* line */ (const char *) "x.CCCC.x   ",
           /* line */ (const char *) "x...CC.xxx ",
           /* line */ (const char *) "xx..CC...x ",
           /* line */ (const char *) " x..cC.@.x ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x......Bx ",
           /* line */ (const char *) " x........^",
           /* line */ (const char *) " xxxxxxxxx ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) " xB.......^",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) "^........x ",
           /* line */ (const char *) " x...@...x ",
           /* line */ (const char *) " xxxxxx.xx ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^      ",
           /* line */ (const char *) " xxx.xxxxx ",
           /* line */ (const char *) " xB......x ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) "^........x ",
           /* line */ (const char *) " x...@...x ",
           /* line */ (const char *) " xxxxxxxxx ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) " xxxx.xxxx ",
           /* line */ (const char *) " xB......x ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x.......x ",
           /* line */ (const char *) " x...@....^",
           /* line */ (const char *) " xxxxxxxxx ",
           /* line */ (const char *) "           ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^          ",
           /* line */ (const char *) " xxxx.xxxx      ",
           /* line */ (const char *) "^........x      ",
           /* line */ (const char *) " x.......x      ",
           /* line */ (const char *) " x.......x      ",
           /* line */ (const char *) " x.......x      ",
           /* line */ (const char *) " xxxxxx..x      ",
           /* line */ (const char *) "      x..xxxxxx ",
           /* line */ (const char *) "      x.......x ",
           /* line */ (const char *) "      x.......x ",
           /* line */ (const char *) "      x.......x ",
           /* line */ (const char *) "      xB..@...x ",
           /* line */ (const char *) "      xxxxxxxxx ",
           /* line */ (const char *) "                ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^          ",
           /* line */ (const char *) " xxxx.xxxx      ",
           /* line */ (const char *) "^........x      ",
           /* line */ (const char *) " x.......x      ",
           /* line */ (const char *) " xxxxxx..x      ",
           /* line */ (const char *) "      x..xxxxxx ",
           /* line */ (const char *) "      x......Bx ",
           /* line */ (const char *) "      x...@...x ",
           /* line */ (const char *) "      xxxxxxxxx ",
           /* line */ (const char *) "                ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^          ",
           /* line */ (const char *) " xxxx.xxxxx     ",
           /* line */ (const char *) "^.........xx    ",
           /* line */ (const char *) " x.........xx   ",
           /* line */ (const char *) " xxxxxx.....xx  ",
           /* line */ (const char *) "      x......xx ",
           /* line */ (const char *) "      x.......x ",
           /* line */ (const char *) "      x...@..Bx ",
           /* line */ (const char *) "      xxxxxxxxx ",
           /* line */ (const char *) "                ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_CHECK_EXITS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^          ",
           /* line */ (const char *) " xxxx.xxxxx     ",
           /* line */ (const char *) "^.........xx    ",
           /* line */ (const char *) " x.........xx   ",
           /* line */ (const char *) " x..........xx  ",
           /* line */ (const char *) " xx..........xx ",
           /* line */ (const char *) "  xx..........x ",
           /* line */ (const char *) "   xx.....@..Bx ",
           /* line */ (const char *) "    xxxxxxxxxxx ",
           /* line */ (const char *) "                ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "      ^   ",
           /* line */ (const char *) "  xxxx.x  ",
           /* line */ (const char *) " xx.....x ",
           /* line */ (const char *) " xB.....x ",
           /* line */ (const char *) " x...@..x ",
           /* line */ (const char *) "^.......x ",
           /* line */ (const char *) " xx......^",
           /* line */ (const char *) "  xxxxx.x ",
           /* line */ (const char *) "       ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ^         ",
           /* line */ (const char *) " x.xxxx     ",
           /* line */ (const char *) " x.B..xx    ",
           /* line */ (const char *) " x.....xx   ",
           /* line */ (const char *) " x......x   ",
           /* line */ (const char *) "^.......xx  ",
           /* line */ (const char *) " xx......xx ",
           /* line */ (const char *) "  x.......x ",
           /* line */ (const char *) " xxx...@..x ",
           /* line */ (const char *) " x$xsx....x ",
           /* line */ (const char *) " x...xxxx.x ",
           /* line */ (const char *) " x...x  x.x ",
           /* line */ (const char *) " xxxxx  x.x ",
           /* line */ (const char *) "         ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "  xxx.xxx  ",
           /* line */ (const char *) "  xB....x  ",
           /* line */ (const char *) " xx.....x  ",
           /* line */ (const char *) "^.......x  ",
           /* line */ (const char *) " xxx....xxx",
           /* line */ (const char *) "   xx.....x",
           /* line */ (const char *) "    x..@..x",
           /* line */ (const char *) "    x.....x",
           /* line */ (const char *) "    xxxxxxx",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^      ",
           /* line */ (const char *) "      xx.xxxx  ",
           /* line */ (const char *) "     xx.....xx ",
           /* line */ (const char *) "  xxxx.......x ",
           /* line */ (const char *) " xxB..........^",
           /* line */ (const char *) "^............x ",
           /* line */ (const char *) " x........@..x ",
           /* line */ (const char *) " x..........xx ",
           /* line */ (const char *) " xx....xxxxxx  ",
           /* line */ (const char *) "  xxxxxx       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "        ^      ",
           /* line */ (const char *) "      xx.xxxx  ",
           /* line */ (const char *) "     xx....Bxx ",
           /* line */ (const char *) "  xxxx.......x ",
           /* line */ (const char *) "^............x ",
           /* line */ (const char *) " x..@.......xx ",
           /* line */ (const char *) " xx....xxxxxx  ",
           /* line */ (const char *) "  xxxxxx       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  xxxxxx  ",
           /* line */ (const char *) " xx....xx ",
           /* line */ (const char *) " x......x ",
           /* line */ (const char *) " x.......^",
           /* line */ (const char *) "^.......x ",
           /* line */ (const char *) " x....@.x ",
           /* line */ (const char *) " xxB....x ",
           /* line */ (const char *) "  xxxxxxx ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^   ",
           /* line */ (const char *) "   xxxxxx.xx ",
           /* line */ (const char *) "  xx.......x ",
           /* line */ (const char *) "  x........x ",
           /* line */ (const char *) " xx.........^",
           /* line */ (const char *) " x...@...xxx ",
           /* line */ (const char *) " x.......x   ",
           /* line */ (const char *) "^........x   ",
           /* line */ (const char *) " xxB....Bx   ",
           /* line */ (const char *) "  xxxxxxxx   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^   ",
           /* line */ (const char *) "   xxxxxx.xx ",
           /* line */ (const char *) "  xx....B..x ",
           /* line */ (const char *) "  x........x ",
           /* line */ (const char *) " xx.........^",
           /* line */ (const char *) "^....@....xx ",
           /* line */ (const char *) " x.......xx  ",
           /* line */ (const char *) " xxxxxxxxx   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "         ^   ",
           /* line */ (const char *) "   xxxxxx.xx ",
           /* line */ (const char *) "  xx....B..x ",
           /* line */ (const char *) "  x........x ",
           /* line */ (const char *) " xx.........^",
           /* line */ (const char *) " x.........x ",
           /* line */ (const char *) " x.........x ",
           /* line */ (const char *) "^........@.x ",
           /* line */ (const char *) " xx........x ",
           /* line */ (const char *) "  xxxxxxxxxx ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   xxxxxxxxx ",
           /* line */ (const char *) "  xx...s..$x ",
           /* line */ (const char *) "  x....xxxxx ",
           /* line */ (const char *) " xx.........^",
           /* line */ (const char *) " x.....xxxxx ",
           /* line */ (const char *) " x.........x ",
           /* line */ (const char *) "^........@.x ",
           /* line */ (const char *) " xxB.......x ",
           /* line */ (const char *) "  xxxxxxxxxx ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   xxxxxxxxx ",
           /* line */ (const char *) "  xx...s..mx ",
           /* line */ (const char *) "  x....xxxxx ",
           /* line */ (const char *) " xx.........^",
           /* line */ (const char *) " x.....xxxxx ",
           /* line */ (const char *) "^..........x ",
           /* line */ (const char *) " x.......@.x ",
           /* line */ (const char *) " xxB.......x ",
           /* line */ (const char *) "  xxxxxxxxxx ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   xxxxx     ",
           /* line */ (const char *) "  xxB..x     ",
           /* line */ (const char *) "  x....xxxxx ",
           /* line */ (const char *) " xx.........^",
           /* line */ (const char *) " x.....xxxxx ",
           /* line */ (const char *) " x.........x ",
           /* line */ (const char *) "^........@.x ",
           /* line */ (const char *) " xx........x ",
           /* line */ (const char *) "  xxxxxxxxxx ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   xxxxx     ",
           /* line */ (const char *) "  xxB..x     ",
           /* line */ (const char *) " xx....xxxxx ",
           /* line */ (const char *) "^...@.......^",
           /* line */ (const char *) " x.....xxxxx ",
           /* line */ (const char *) " xxxxxxx     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   xxxxx     ",
           /* line */ (const char *) "  xxB..x     ",
           /* line */ (const char *) " xx....xxxxx ",
           /* line */ (const char *) "^...@......x ",
           /* line */ (const char *) " x..........^",
           /* line */ (const char *) " x.....xxxxx ",
           /* line */ (const char *) " xxxxxxx     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   xxxxx     ",
           /* line */ (const char *) "  xxB..x     ",
           /* line */ (const char *) " xx....xxxxx ",
           /* line */ (const char *) "^...@......x ",
           /* line */ (const char *) " x.........x ",
           /* line */ (const char *) " x.B.B......^",
           /* line */ (const char *) " x.....xxxxx ",
           /* line */ (const char *) " xxxxxxx     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   xxxxx     ",
           /* line */ (const char *) "  xxB..x     ",
           /* line */ (const char *) " xx....xxxxx ",
           /* line */ (const char *) "^...@.....Bx ",
           /* line */ (const char *) " x.........x ",
           /* line */ (const char *) " x..CCCCCC.x ",
           /* line */ (const char *) " x.CCCCCCC.x ",
           /* line */ (const char *) " x.CCCCCC..x ",
           /* line */ (const char *) " x..........^",
           /* line */ (const char *) " xB...Bxxxxx ",
           /* line */ (const char *) " xxxxxxx     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   xxxxx     ",
           /* line */ (const char *) "  xxB..x     ",
           /* line */ (const char *) " xx....xxxxx ",
           /* line */ (const char *) "^...@..CCCCx ",
           /* line */ (const char *) " x....CCCCCx ",
           /* line */ (const char *) " x..CCCCCC.x ",
           /* line */ (const char *) " x.CCCCCCC.x ",
           /* line */ (const char *) " x.CCCCCCC.x ",
           /* line */ (const char *) " x.=======.x ",
           /* line */ (const char *) " xCCCCCCC..x ",
           /* line */ (const char *) " xCCCCCC....^",
           /* line */ (const char *) " xB.$.Bxxxxx ",
           /* line */ (const char *) " xxxxxxx     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   xxxxx     ",
           /* line */ (const char *) "  xxB..x     ",
           /* line */ (const char *) " xx....xxxxx ",
           /* line */ (const char *) "^...@..CCCCx ",
           /* line */ (const char *) " x....CCCCCx ",
           /* line */ (const char *) " x..CCCCCCCx ",
           /* line */ (const char *) " x.CCCCCCCCx ",
           /* line */ (const char *) " x.=======.x ",
           /* line */ (const char *) " xCCCCCCCC.x ",
           /* line */ (const char *) " xC=======.x ",
           /* line */ (const char *) " xC.CCCCC..x ",
           /* line */ (const char *) " xC.CCCC....^",
           /* line */ (const char *) " xB.$.Bxxxxx ",
           /* line */ (const char *) " xxxxxxx     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, 0 /* check */, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   xxxxx     ",
           /* line */ (const char *) "  xxB..x     ",
           /* line */ (const char *) " xx....xxxxx ",
           /* line */ (const char *) "^...@.....Bx ",
           /* line */ (const char *) " x.........x ",
           /* line */ (const char *) " x..CC=CCC.x ",
           /* line */ (const char *) " xCCCC=CCCCx ",
           /* line */ (const char *) " xCCCC=CCCCx ",
           /* line */ (const char *) " xCCCC=CCCCx ",
           /* line */ (const char *) " xCCCC=CCCCx ",
           /* line */ (const char *) " x.CCC=CCC.x ",
           /* line */ (const char *) " x..........^",
           /* line */ (const char *) " xB...Bxxxxx ",
           /* line */ (const char *) " xxxxxxx     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^     ",
           /* line */ (const char *) " xxxxxx.xxx  ",
           /* line */ (const char *) " xCC....CCxx ",
           /* line */ (const char *) "^........CCx ",
           /* line */ (const char *) " xC......CCx ",
           /* line */ (const char *) " x..........^",
           /* line */ (const char *) " x........CC ",
           /* line */ (const char *) " x.......CCx ",
           /* line */ (const char *) " x......CCxx ",
           /* line */ (const char *) " x..@..xxxx  ",
           /* line */ (const char *) " xx...xx     ",
           /* line */ (const char *) "  xB.Bx      ",
           /* line */ (const char *) "  xxxxx      ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^      ",
           /* line */ (const char *) " xxxxxx.xxxxxx",
           /* line */ (const char *) " xCC....CCC.$x",
           /* line */ (const char *) "^......CCC...x",
           /* line */ (const char *) " xC.....CCC..x",
           /* line */ (const char *) " x.....CCC..Gx",
           /* line */ (const char *) " x......CCC..x",
           /* line */ (const char *) " x.....CCC...x",
           /* line */ (const char *) " x......CCC.$x",
           /* line */ (const char *) " x..@..xxxxxxx",
           /* line */ (const char *) " xx...xx      ",
           /* line */ (const char *) "  xB.Bx       ",
           /* line */ (const char *) "  xxxxx       ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, NO_FLAGS, __FUNCTION__, __LINE__,
           /* line */ (const char *) "       ^      ",
           /* line */ (const char *) " xxxxxx.xxxxxx",
           /* line */ (const char *) " xCC....CCCCCx",
           /* line */ (const char *) "^......CCCCCCx",
           /* line */ (const char *) " xC...=====..x",
           /* line */ (const char *) " xC...CCCCC.Gx",
           /* line */ (const char *) " xC...CCCCC..x",
           /* line */ (const char *) " xC...CCC....x",
           /* line */ (const char *) " xC...CCC...$x",
           /* line */ (const char *) " xC.@.Cxxxxxxx",
           /* line */ (const char *) " xx...xx      ",
           /* line */ (const char *) "  xB.Bx       ",
           /* line */ (const char *) "  xxxxx       ",
           /* end */ nullptr);
}
