//
// Copyright goblinhack@gmail.com
//

#include "my_callstack.hpp"
#include "my_level.hpp"
#include "my_types.hpp"

//
// Create all key rooms
//
void rooms_prefab_key(Gamep g)
{
  TRACE();

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " ..M.......^",
           /* line */ (const char *) " ....````.. ",
           /* line */ (const char *) " ....`v+vvv ",
           /* line */ (const char *) " ....`v...v ",
           /* line */ (const char *) "^.....vv..v ",
           /* line */ (const char *) " ......v.kv ",
           /* line */ (const char *) " ......vvvv ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " ..vvvvvv..^",
           /* line */ (const char *) " ..v.```v`. ",
           /* line */ (const char *) " ..v.`v+vsv ",
           /* line */ (const char *) " ..vk`vbb.v ",
           /* line */ (const char *) "^..vvvvvb.v ",
           /* line */ (const char *) " ......v..v ",
           /* line */ (const char *) " ......vvvv ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " ....C..... ",
           /* line */ (const char *) " .CCCCCCCC. ",
           /* line */ (const char *) " .CvvvvvvC.^",
           /* line */ (const char *) " .CvM```vCC ",
           /* line */ (const char *) " .Cv...`vC. ",
           /* line */ (const char *) " CCvk..``C. ",
           /* line */ (const char *) "^.CvvvvvvC. ",
           /* line */ (const char *) " .CCCCCCCC. ",
           /* line */ (const char *) " ....C..... ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " C......... ",
           /* line */ (const char *) " ...vvvv... ",
           /* line */ (const char *) " ..CvvvvC..^",
           /* line */ (const char *) " .vvM```vv. ",
           /* line */ (const char *) " .vv...`vv. ",
           /* line */ (const char *) " .vvk..`vv. ",
           /* line */ (const char *) "^..Cvv+vC.. ",
           /* line */ (const char *) " ...vv+v... ",
           /* line */ (const char *) " .........C ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " ....       ",
           /* line */ (const char *) " . .......  ",
           /* line */ (const char *) " . .     ..^",
           /* line */ (const char *) " . . ... .  ",
           /* line */ (const char *) " . . .k. .  ",
           /* line */ (const char *) " . .   . .  ",
           /* line */ (const char *) "^. ..... .  ",
           /* line */ (const char *) " .       .  ",
           /* line */ (const char *) " .........  ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " ....       ",
           /* line */ (const char *) " .C.......  ",
           /* line */ (const char *) " .C.CCCCC..^",
           /* line */ (const char *) " .C.C...C.  ",
           /* line */ (const char *) " .C.C.k.C.  ",
           /* line */ (const char *) " .C.CCC.C.  ",
           /* line */ (const char *) "^.C.....C.  ",
           /* line */ (const char *) " .CCCCCCC.  ",
           /* line */ (const char *) " .........  ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " ....       ",
           /* line */ (const char *) " .........  ",
           /* line */ (const char *) " ..CCCCC...^",
           /* line */ (const char *) " .CCC..CC.  ",
           /* line */ (const char *) " .CCCCCCC.  ",
           /* line */ (const char *) " .CC..CCC.  ",
           /* line */ (const char *) " .CCCCCCC.  ",
           /* line */ (const char *) " .CCC..CC.  ",
           /* line */ (const char *) " .CCCCCCC.  ",
           /* line */ (const char *) " .CC..CCC.  ",
           /* line */ (const char *) "^.CC.k.CC.  ",
           /* line */ (const char *) " .CCC..CC.  ",
           /* line */ (const char *) "..CCCCCCC.  ",
           /* line */ (const char *) " ..CCCCC..  ",
           /* line */ (const char *) " .........  ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " ....       ",
           /* line */ (const char *) " .........  ",
           /* line */ (const char *) " ..LLLLL...^",
           /* line */ (const char *) " .LLL..LL.  ",
           /* line */ (const char *) " .LLLLLLL.  ",
           /* line */ (const char *) " .LL..LLL.  ",
           /* line */ (const char *) " .LLLLLLL.  ",
           /* line */ (const char *) " .LLL..LL.  ",
           /* line */ (const char *) " .LLLLLLL.  ",
           /* line */ (const char *) " .LL..LLL.  ",
           /* line */ (const char *) "^.LL.k.LL.  ",
           /* line */ (const char *) " .LLL..LL.  ",
           /* line */ (const char *) "..LLLLLLL.  ",
           /* line */ (const char *) " ..LLLLL..  ",
           /* line */ (const char *) " .........  ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " .........  ",
           /* line */ (const char *) " .......m.  ",
           /* line */ (const char *) " ....CC....^",
           /* line */ (const char *) " ...CCCC..  ",
           /* line */ (const char *) " ..CC.kCC.  ",
           /* line */ (const char *) " ..CC..CC.  ",
           /* line */ (const char *) "^...CCCC..  ",
           /* line */ (const char *) " ....CC...  ",
           /* line */ (const char *) " .........  ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " ....C...k  ",
           /* line */ (const char *) " ....CC..m  ",
           /* line */ (const char *) " ....CCCC.. ",
           /* line */ (const char *) " ......CCC  ",
           /* line */ (const char *) " ........C  ",
           /* line */ (const char *) " .........  ",
           /* line */ (const char *) "^.........  ",
           /* line */ (const char *) " .........  ",
           /* line */ (const char *) " .........  ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " k.C......  ",
           /* line */ (const char *) " m.C......  ",
           /* line */ (const char *) " ..C.......^",
           /* line */ (const char *) " ..C......  ",
           /* line */ (const char *) " ..C......  ",
           /* line */ (const char *) " CCC......  ",
           /* line */ (const char *) "^.........  ",
           /* line */ (const char *) " .........  ",
           /* line */ (const char *) " .........  ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " ...CC.CC..^",
           /* line */ (const char *) " ..C..C..C. ",
           /* line */ (const char *) " ...CCkCC.. ",
           /* line */ (const char *) "^..C..C..C. ",
           /* line */ (const char *) " ...CC.CC.. ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    ^       ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " ...LL.LL..^",
           /* line */ (const char *) " ..L..L..L. ",
           /* line */ (const char *) " ...LLkLL.. ",
           /* line */ (const char *) "^..L..L..L. ",
           /* line */ (const char *) " ...LL.LL.. ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vk..v   ",
           /* line */ (const char *) "    v.M.v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "    vB.Bv   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vv.vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vk..v   ",
           /* line */ (const char *) "    v.G.v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vk..v   ",
           /* line */ (const char *) "    vCCCv   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vk.$v   ",
           /* line */ (const char *) "    v.M.v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);
  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vk..v   ",
           /* line */ (const char *) "    vLLLv   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);
  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vk..v   ",
           /* line */ (const char *) "    v.M.v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vCtCv   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);
  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vk.$v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);
  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vk.Gv   ",
           /* line */ (const char *) "    v.v.v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);
  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vk.Bv   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);
  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vk..v   ",
           /* line */ (const char *) "    v.|.v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vk..v   ",
           /* line */ (const char *) "    v.M.v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vk.Gv   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vk.Bv   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vB.Bv   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vCCCv   ",
           /* line */ (const char *) "    vCkCv   ",
           /* line */ (const char *) "    vCCCv   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vLLLv   ",
           /* line */ (const char *) "    vLkLv   ",
           /* line */ (const char *) "    vLLLv   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vk.$v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    v$.$v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    vvvvv   ",
           /* line */ (const char *) "    vk.Gv   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) " vvvvv+vv   ",
           /* line */ (const char *) " v$.s...v   ",
           /* line */ (const char *) " vvvvv+vv   ",
           /* line */ (const char *) "    v...v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvvvvv   ",
           /* line */ (const char *) "v$..sk..v   ",
           /* line */ (const char *) "v...v.M.v   ",
           /* line */ (const char *) "vvvvv...v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvvvvv   ",
           /* line */ (const char *) "v$.tsk..v   ",
           /* line */ (const char *) "v...v.M.v   ",
           /* line */ (const char *) "vvvvv...v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvvvvv   ",
           /* line */ (const char *) "v$.Csk..v   ",
           /* line */ (const char *) "v..Cv.M.v   ",
           /* line */ (const char *) "vvvvv...v   ",
           /* line */ (const char *) "    vv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvvvvv   ",
           /* line */ (const char *) "vk......v   ",
           /* line */ (const char *) "v``...G.v   ",
           /* line */ (const char *) "v+vvv...v   ",
           /* line */ (const char *) "v...v...v   ",
           /* line */ (const char *) "v..$v...v   ",
           /* line */ (const char *) "vvvvvv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvvvvv   ",
           /* line */ (const char *) "vk.CC...v   ",
           /* line */ (const char *) "v``CC.G.v   ",
           /* line */ (const char *) "v+vvv...v   ",
           /* line */ (const char *) "v...v...v   ",
           /* line */ (const char *) "v..$v...v   ",
           /* line */ (const char *) "vvvvvv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvvvvv   ",
           /* line */ (const char *) "vk.``...v   ",
           /* line */ (const char *) "v````.G.v   ",
           /* line */ (const char *) "v+vvv...v   ",
           /* line */ (const char *) "v...v...v   ",
           /* line */ (const char *) "v..$v...v   ",
           /* line */ (const char *) "vvvvvv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvvvvv   ",
           /* line */ (const char *) "vk.LL...v   ",
           /* line */ (const char *) "v``.L.G.v   ",
           /* line */ (const char *) "v+vvvL..v   ",
           /* line */ (const char *) "v...vL..v   ",
           /* line */ (const char *) "v..$vL..v   ",
           /* line */ (const char *) "vvvvvv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "vvvvvvvvv   ",
           /* line */ (const char *) "vk.CCC.Gv   ",
           /* line */ (const char *) "v``.CC..v   ",
           /* line */ (const char *) "v+vvvC..v   ",
           /* line */ (const char *) "v...vC..v   ",
           /* line */ (const char *) "v..$vC..v   ",
           /* line */ (const char *) "vvvvvv+vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " .C....... ",
           /* line */ (const char *) "^.C..k..T. ",
           /* line */ (const char *) " .C....... ",
           /* line */ (const char *) " .CCCC.... ",
           /* line */ (const char *) " ....C.... ",
           /* line */ (const char *) " ..CGC.... ",
           /* line */ (const char *) " ..===.... ",
           /* line */ (const char *) " ..CGC.... ",
           /* line */ (const char *) " ..CCCCC.. ",
           /* line */ (const char *) " ......C..^",
           /* line */ (const char *) " T.....C.. ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " .L.....L. ",
           /* line */ (const char *) "^.L..k.... ",
           /* line */ (const char *) " .L....L.. ",
           /* line */ (const char *) " ..LLLL... ",
           /* line */ (const char *) " ....L..L. ",
           /* line */ (const char *) " .LLGLLL.. ",
           /* line */ (const char *) " ......... ",
           /* line */ (const char *) " ..LGL.LL. ",
           /* line */ (const char *) " .LLLLLLL. ",
           /* line */ (const char *) " LL...LL..^",
           /* line */ (const char *) " ...LLLL.. ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " .C.....C. ",
           /* line */ (const char *) "^.C..kCC.. ",
           /* line */ (const char *) " .C..CCC.. ",
           /* line */ (const char *) " .CCCCC... ",
           /* line */ (const char *) " ....C.... ",
           /* line */ (const char *) " .CCGCCCC. ",
           /* line */ (const char *) " .=======. ",
           /* line */ (const char *) " .CCGCCCC. ",
           /* line */ (const char *) " .CCCCCCC. ",
           /* line */ (const char *) " CC...CC..^",
           /* line */ (const char *) " ...CCCC.. ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " .C....... ",
           /* line */ (const char *) "^.C..k.... ",
           /* line */ (const char *) " .C....... ",
           /* line */ (const char *) " .CCCC.... ",
           /* line */ (const char *) " ....C.... ",
           /* line */ (const char *) " ..CGC.... ",
           /* line */ (const char *) " ..===.... ",
           /* line */ (const char *) " ..CGC.... ",
           /* line */ (const char *) " ..CCCCC.. ",
           /* line */ (const char *) " ......C..^",
           /* line */ (const char *) " ......C.. ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ..=CC.kg",
           /* line */ (const char *) "...=CC...",
           /* line */ (const char *) "...=CCCCC",
           /* line */ (const char *) "====CCC  ",
           /* line */ (const char *) "CCCCC....",
           /* line */ (const char *) "C..m.C...",
           /* line */ (const char *) "CC...C..C",
           /* line */ (const char *) "      ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    CCCC   ",
           /* line */ (const char *) " CCCCCCCCC ",
           /* line */ (const char *) "^=========^",
           /* line */ (const char *) " CCCCCCCCC ",
           /* line */ (const char *) "  CCCC..CC ",
           /* line */ (const char *) "    CCk.CC ",
           /* line */ (const char *) "    CC..C  ",
           /* line */ (const char *) "     C..   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " ..=C...g",
           /* line */ (const char *) "...=C....",
           /* line */ (const char *) "...=Ck..`",
           /* line */ (const char *) "====C..  ",
           /* line */ (const char *) "CCCCC....",
           /* line */ (const char *) "L..m.L...",
           /* line */ (const char *) "LL...L..L",
           /* line */ (const char *) "      ^  ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  .......g ",
           /* line */ (const char *) "^......... ",
           /* line */ (const char *) " |....k... ",
           /* line */ (const char *) " ...CCCC..^",
           /* line */ (const char *) " |.CCCCCC. ",
           /* line */ (const char *) " ...m.CCC. ",
           /* line */ (const char *) " B........ ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   LLL...g ",
           /* line */ (const char *) "   LL..... ",
           /* line */ (const char *) "   LL.LLLL ",
           /* line */ (const char *) "^...L.kL.. ",
           /* line */ (const char *) "   .LLLL.. ",
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) "   `..B.B  ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   B...LLL ",
           /* line */ (const char *) "   .....LL ",
           /* line */ (const char *) "   ......L ",
           /* line */ (const char *) "^.....g..L ",
           /* line */ (const char *) "   .......^",
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) " LL......B ",
           /* line */ (const char *) "LLkLL  .   ",
           /* line */ (const char *) "LLLL   .   ",
           /* line */ (const char *) "LL     ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   .....LL ",
           /* line */ (const char *) "   ......L ",
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) "^.....g... ",
           /* line */ (const char *) "   .......^",
           /* line */ (const char *) "  L....... ",
           /* line */ (const char *) " LL....... ",
           /* line */ (const char *) " LkLL  .   ",
           /* line */ (const char *) " LLL   .   ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^       ",
           /* line */ (const char *) "   .....LL ",
           /* line */ (const char *) "   ......L ",
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) "^.g....... ",
           /* line */ (const char *) "   .......^",
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) " LLL...... ",
           /* line */ (const char *) " LkLLLL.   ",
           /* line */ (const char *) " .....g.   ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^       ",
           /* line */ (const char *) "   .....CC ",
           /* line */ (const char *) "   ......C ",
           /* line */ (const char *) "   .....C. ",
           /* line */ (const char *) "^.g....C.. ",
           /* line */ (const char *) "   ....C..^",
           /* line */ (const char *) "   ...C... ",
           /* line */ (const char *) " CCC.CC... ",
           /* line */ (const char *) " CkCCCC.   ",
           /* line */ (const char *) " .....g.   ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ^     ",
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) "^.....g... ",
           /* line */ (const char *) "   .......^",
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) " ..B...... ",
           /* line */ (const char *) " .k.   .   ",
           /* line */ (const char *) " ... $ .   ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) "   ..CCCCC ",
           /* line */ (const char *) "   ..C...C ",
           /* line */ (const char *) "^.t..CGC.C ",
           /* line */ (const char *) "   ..CCC.C^",
           /* line */ (const char *) "   ......C ",
           /* line */ (const char *) " .`CCCCCCC ",
           /* line */ (const char *) " .``   .   ",
           /* line */ (const char *) " k.`   .   ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ....... ",
           /* line */ (const char *) "   .....C. ",
           /* line */ (const char *) "   ....C.. ",
           /* line */ (const char *) "^.t.C.C... ",
           /* line */ (const char *) "   .CC....^",
           /* line */ (const char *) "   .CCC... ",
           /* line */ (const char *) " .`....... ",
           /* line */ (const char *) " .``   .   ",
           /* line */ (const char *) " k.`   .   ",
           /* line */ (const char *) "       ^   ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ... ...",
           /* line */ (const char *) "     .T. .T.",
           /* line */ (const char *) " ... ... ..m",
           /* line */ (const char *) "^.T.        ",
           /* line */ (const char *) " ... ... ...",
           /* line */ (const char *) "     .T. .T.",
           /* line */ (const char *) "     ... ..m",
           /* line */ (const char *) "            ",
           /* line */ (const char *) "     ... ...",
           /* line */ (const char *) "     .T. .T.",
           /* line */ (const char *) "     ... ..m",
           /* line */ (const char *) "            ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " .k..M...T. ",
           /* line */ (const char *) " .......... ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "^...LLLLLLLLL",
           /* line */ (const char *) "   LL...L...L",
           /* line */ (const char *) "  LLL.G.L.G.L",
           /* line */ (const char *) " ...L...L...L",
           /* line */ (const char *) "^...LLLLLLLLL",
           /* line */ (const char *) " ...L...L...L",
           /* line */ (const char *) "  LLL.G.L.G.L",
           /* line */ (const char *) "  LLL...L...L",
           /* line */ (const char *) "   LLLLLLLLLL",
           /* line */ (const char *) "   LL...L...L",
           /* line */ (const char *) "    L.G.L.k.L",
           /* line */ (const char *) "    L...L...L",
           /* line */ (const char *) "    LLLLLLLLL",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "^...CCCCCCCCC",
           /* line */ (const char *) "   CC...C...C",
           /* line */ (const char *) "  CCC.G.C.G.C",
           /* line */ (const char *) " ...C...C...C",
           /* line */ (const char *) "^...CCCCCCCCC",
           /* line */ (const char *) " ...C...C...C",
           /* line */ (const char *) "  CCC.G.C.G.C",
           /* line */ (const char *) "  CCC...C...C",
           /* line */ (const char *) "   CCCCCCCCCC",
           /* line */ (const char *) "   CC...C...C",
           /* line */ (const char *) "    C.G.C.k.C",
           /* line */ (const char *) "    C...C...C",
           /* line */ (const char *) "    CCCCCCCCC",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "     ... ...",
           /* line */ (const char *) "     .T. .T.",
           /* line */ (const char *) " ... ... ..m",
           /* line */ (const char *) "^.T.        ",
           /* line */ (const char *) " ... ... ...",
           /* line */ (const char *) "     .T. .T.",
           /* line */ (const char *) "     ... ..m",
           /* line */ (const char *) "            ",
           /* line */ (const char *) " .......... ",
           /* line */ (const char *) " .k..M...T. ",
           /* line */ (const char *) " .......... ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "    CCCCCCCC",
           /* line */ (const char *) "    C..CCC..",
           /* line */ (const char *) "    C..===..",
           /* line */ (const char *) " ...C..CCC.=",
           /* line */ (const char *) "^...CCCCCCC=",
           /* line */ (const char *) " ...CCCCC..=",
           /* line */ (const char *) " CCCCCCCC.G.",
           /* line */ (const char *) " CCCC..CC...",
           /* line */ (const char *) " CCC.G.CCC=C",
           /* line */ (const char *) " CCC..CCCC=C",
           /* line */ (const char *) " CCCCCCCCC=C",
           /* line */ (const char *) " CCCCCCCCC=C",
           /* line */ (const char *) " C...CC....C",
           /* line */ (const char *) " Ck..==....C",
           /* line */ (const char *) " C...CC....C",
           /* line */ (const char *) " CCCCCCCCCCC",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ..........",
           /* line */ (const char *) " ..........`",
           /* line */ (const char *) " ........```",
           /* line */ (const char *) "^...       s",
           /* line */ (const char *) " ... C......",
           /* line */ (const char *) "     CC..M..",
           /* line */ (const char *) "     ..C....",
           /* line */ (const char *) "     ...C...",
           /* line */ (const char *) " ........C..",
           /* line */ (const char *) " .k.......C.",
           /* line */ (const char *) " .........CC",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  ..........",
           /* line */ (const char *) " ..........`",
           /* line */ (const char *) " ........```",
           /* line */ (const char *) "^...       s",
           /* line */ (const char *) " ... `......",
           /* line */ (const char *) "     ``..M..",
           /* line */ (const char *) "     ```....",
           /* line */ (const char *) "     s    CC",
           /* line */ (const char *) "     .   CCC",
           /* line */ (const char *) "     .  CCCC",
           /* line */ (const char *) " ... ...C...",
           /* line */ (const char *) " $..s..CC.k.",
           /* line */ (const char *) " ... .CC....",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  .CC...````",
           /* line */ (const char *) " ..CCC....`.",
           /* line */ (const char *) " ..CCCC....`",
           /* line */ (const char *) "^...CCC.M...",
           /* line */ (const char *) " ...CC......",
           /* line */ (const char *) " v..CCCCB...",
           /* line */ (const char *) " vv.=====...",
           /* line */ (const char *) " vvvvCCCB...",
           /* line */ (const char *) " vvvvCCCCC..",
           /* line */ (const char *) " vvvvvvvCCCC",
           /* line */ (const char *) " .k...BvvvC`",
           /* line */ (const char *) " $........s`",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  .LL...````",
           /* line */ (const char *) " ..LLL....`.",
           /* line */ (const char *) " ..LLLL....`",
           /* line */ (const char *) "^...LLL.M...",
           /* line */ (const char *) " ...LL......",
           /* line */ (const char *) " v..LLLL....",
           /* line */ (const char *) " vv.=====...",
           /* line */ (const char *) " vvvvLLLLLL.",
           /* line */ (const char *) " vvvvvvvLLLL",
           /* line */ (const char *) " .k...BvvvL.",
           /* line */ (const char *) " $........s.",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  CCCCCCCCCCC",
           /* line */ (const char *) " CC.CCC.C..kC",
           /* line */ (const char *) " CCCCCCCC...C",
           /* line */ (const char *) "^========...C",
           /* line */ (const char *) " CCCCCCCC...C",
           /* line */ (const char *) " CCCC.CCC..MC",
           /* line */ (const char *) "  CCCCCCCCCCC",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " CCCCCCCCCCCCCCCCCCC",
           /* line */ (const char *) " CBCCCC...CCCCBC...C",
           /* line */ (const char *) "^======.G.======.k.C",
           /* line */ (const char *) " CBCCCC...CCCCBC...C",
           /* line */ (const char *) " CCCCCCCCCCCCCCCCCCC",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  CCCCCCCCCCC",
           /* line */ (const char *) " CCCCCCCCCCCC",
           /* line */ (const char *) "^========...C",
           /* line */ (const char *) " CCCCCCCC...C",
           /* line */ (const char *) " CCCCCCCC.M.C",
           /* line */ (const char *) " C=======...C",
           /* line */ (const char *) " CCCCCCCC...C",
           /* line */ (const char *) " v.vvvvvv``.C",
           /* line */ (const char *) " v.....kv``.C",
           /* line */ (const char *) " vvvvvvvvCCCC",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  LLLLLLLLLLL",
           /* line */ (const char *) " LL.LLL.L..kL",
           /* line */ (const char *) " LLLLLLLL...L",
           /* line */ (const char *) "^========...L",
           /* line */ (const char *) " LLLLLLLL...L",
           /* line */ (const char *) " LLLL.LLL..ML",
           /* line */ (const char *) "  LLLLLLLLLLL",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " LLLLLLLLLLLLLLLLLLL",
           /* line */ (const char *) " LBLLLL...LLLLBL...L",
           /* line */ (const char *) "^======.G.======.k.L",
           /* line */ (const char *) " LBLLLL...LLLLBL...L",
           /* line */ (const char *) " LLLLLLLLLLLLLLLLLLL",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  LLLLLLLLLLL",
           /* line */ (const char *) " LLLLLLLLLLLL",
           /* line */ (const char *) "^========...L",
           /* line */ (const char *) " LLLLLLLL...L",
           /* line */ (const char *) " LLLLLLLL.M.L",
           /* line */ (const char *) " L=======...L",
           /* line */ (const char *) " LLLLLLLL...L",
           /* line */ (const char *) " v.vvvvvv``.L",
           /* line */ (const char *) " v.....kv``.L",
           /* line */ (const char *) " vvvvvvvvLLLL",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "  LLLLLLLLLLL",
           /* line */ (const char *) " LL.LLL.L..kL",
           /* line */ (const char *) " LLLLLLLL...L",
           /* line */ (const char *) "^========...L",
           /* line */ (const char *) " LLLLLLLL...L",
           /* line */ (const char *) " LLLL.LLL..ML",
           /* line */ (const char *) "  LLLLLLLLLLL",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* line */ (const char *) " CCvBCCCCCCCv",
           /* line */ (const char *) "^===.......Cv",
           /* line */ (const char *) " CCvBCCCCC.Cv",
           /* line */ (const char *) " CCvCCCCCC.Cv",
           /* line */ (const char *) " CCvCG..CC.Cv",
           /* line */ (const char *) " vvvC..kCC.Cv",
           /* line */ (const char *) " CCvC...CC.Cv",
           /* line */ (const char *) " vCCC.CCCC.Cv",
           /* line */ (const char *) " vC........Cv",
           /* line */ (const char *) " vCCCCCCCCCCv",
           /* line */ (const char *) " vvvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* line */ (const char *) " CCvB..v.C..v",
           /* line */ (const char *) "^===...s.Ct.v",
           /* line */ (const char *) " CCvBvvv.C..v",
           /* line */ (const char *) " CCv...vvvv+v",
           /* line */ (const char *) " vvv.k.v....v",
           /* line */ (const char *) " v.....v....v",
           /* line */ (const char *) " v.G...v....v",
           /* line */ (const char *) " v.....s....v",
           /* line */ (const char *) " vvvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* line */ (const char *) " CCvB.B.....v",
           /* line */ (const char *) "^===......G.v",
           /* line */ (const char *) " CCvB.B.....v",
           /* line */ (const char *) " CCvvvvvvvv+v",
           /* line */ (const char *) " vvv..tC....v",
           /* line */ (const char *) " v.....CCC..v",
           /* line */ (const char *) " v.k..G.CCC.v",
           /* line */ (const char *) " v.......CCCv",
           /* line */ (const char *) " vvvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* line */ (const char *) " CCvB...Ct..v",
           /* line */ (const char *) "^===....CC..v",
           /* line */ (const char *) " CCvB...CC..v",
           /* line */ (const char *) " CCv....CC..v",
           /* line */ (const char *) " vvvCCCCCC..v",
           /* line */ (const char *) " vCCCCCCCC..v",
           /* line */ (const char *) " v..........v",
           /* line */ (const char *) " vG........kv",
           /* line */ (const char *) " vvvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* line */ (const char *) " CCvB.......v",
           /* line */ (const char *) "^===........v",
           /* line */ (const char *) " CCvB.......v",
           /* line */ (const char *) " CCv....C...v",
           /* line */ (const char *) " vvv...CCC..v",
           /* line */ (const char *) " v....CCkCC.v",
           /* line */ (const char *) " v.....CCC..v",
           /* line */ (const char *) " v..G...C...v",
           /* line */ (const char *) " v..........v",
           /* line */ (const char *) " vvvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* line */ (const char *) " CCvBWWWWWWWv",
           /* line */ (const char *) "^===WWWWWWWWv",
           /* line */ (const char *) " CCvBWWWWWWWv",
           /* line */ (const char *) " CCvWWWWWWWWv",
           /* line */ (const char *) " vvvWWWWWWWWv",
           /* line */ (const char *) " vWWWWWWWWWWv",
           /* line */ (const char *) " vWWWWWWWWWWv",
           /* line */ (const char *) " vWWWWWWWWWkv",
           /* line */ (const char *) " vvvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* line */ (const char *) " CCvBCCCC.CCv",
           /* line */ (const char *) "^===.C.CCCCCv",
           /* line */ (const char *) " CCvBCCCCCC.v",
           /* line */ (const char *) " CCvCCCC.CCCv",
           /* line */ (const char *) " vvvCCCCCCCCv",
           /* line */ (const char *) " vCCC.CCCCCCv",
           /* line */ (const char *) " vCCCCCC....v",
           /* line */ (const char *) " vCCCCCC...kv",
           /* line */ (const char *) " vvvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* line */ (const char *) " CCvB.......v",
           /* line */ (const char *) "^===......G.v",
           /* line */ (const char *) " CCvB.......v",
           /* line */ (const char *) " CCv..vvvvv.v",
           /* line */ (const char *) " vvv..v.k.v.v",
           /* line */ (const char *) " v...`v...v.v",
           /* line */ (const char *) " v...`v+vvv.v",
           /* line */ (const char *) " v..`````...v",
           /* line */ (const char *) " vvvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* line */ (const char *) " CCvB..CC...v",
           /* line */ (const char *) "^===...CC.k.v",
           /* line */ (const char *) " CCvB..CC...v",
           /* line */ (const char *) " CCv..CCC...v",
           /* line */ (const char *) " vvv..==....v",
           /* line */ (const char *) " v....CCCC..v",
           /* line */ (const char *) " v..G....CC.v",
           /* line */ (const char *) " v.......CC.v",
           /* line */ (const char *) " vvvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* line */ (const char *) " CCv......C.v",
           /* line */ (const char *) "^===......t.v",
           /* line */ (const char *) " CCvvvvvvvv.v",
           /* line */ (const char *) " CCv......v.v",
           /* line */ (const char *) " vvv.vvvv.v.v",
           /* line */ (const char *) " v...vkG..v.v",
           /* line */ (const char *) " v.vvvvvvvv.v",
           /* line */ (const char *) " v.G........v",
           /* line */ (const char *) " vvvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* line */ (const char *) " CCvB......Gv",
           /* line */ (const char *) "^===...v....v",
           /* line */ (const char *) " CCvB.vvv...v",
           /* line */ (const char *) " CCv...v....v",
           /* line */ (const char *) " vvv.....v..v",
           /* line */ (const char *) " v......vvv.v",
           /* line */ (const char *) " v.......v..v",
           /* line */ (const char *) " vG........kv",
           /* line */ (const char *) " vvvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* line */ (const char *) " CCvB.......v",
           /* line */ (const char *) "^===......G.v",
           /* line */ (const char *) " CCvB.......v",
           /* line */ (const char *) " CCv........v",
           /* line */ (const char *) " vvv.....CCCv",
           /* line */ (const char *) " v.....CCCCCv",
           /* line */ (const char *) " v....CCC...v",
           /* line */ (const char *) " v....CCC..kv",
           /* line */ (const char *) " vvvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* line */ (const char *) " CCvB......Gv",
           /* line */ (const char *) "^===......k.v",
           /* line */ (const char *) " CCvB......Gv",
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* line */ (const char *) " CCvBCC.....v",
           /* line */ (const char *) "^======...G.v",
           /* line */ (const char *) " CCvBCC.....v",
           /* line */ (const char *) " CCvvvv+vvvvv",
           /* line */ (const char *) " vvv..v.v...v",
           /* line */ (const char *) " v....v.v...v",
           /* line */ (const char *) " v.k..v.v..$v",
           /* line */ (const char *) " v......st.$v",
           /* line */ (const char *) " vvvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* line */ (const char *) " CCvB.......v",
           /* line */ (const char *) "^===t.....k.v",
           /* line */ (const char *) " CCvB.......v",
           /* line */ (const char *) " CCvvvvvvvvvv",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) "   ^      ",
           /* line */ (const char *) "vv...vv   ",
           /* line */ (const char *) "v.....v   ",
           /* line */ (const char *) "v.....vv  ",
           /* line */ (const char *) "v.C=C..v  ",
           /* line */ (const char *) "vCC=CC.vv ",
           /* line */ (const char *) "vCC=CCCCvv",
           /* line */ (const char *) "vCC=CCtCCv",
           /* line */ (const char *) "vvC=.....v",
           /* line */ (const char *) " vv...k..v",
           /* line */ (const char *) "  vvv...vv",
           /* line */ (const char *) "    vvvvv ",
           /* end */ nullptr);

  room_add(g, CHANCE_NORMAL, ROOM_FLAG_HAS_KEY, __FUNCTION__, __LINE__,
           /* line */ (const char *) " vvvvvvvvvvv",
           /* line */ (const char *) " v.........v",
           /* line */ (const char *) " v...BkB.M.v",
           /* line */ (const char *) " v.........v",
           /* line */ (const char *) " vvvvCCCvvvv",
           /* line */ (const char *) "    vC.Cv   ",
           /* line */ (const char *) "    vC.Bv   ",
           /* line */ (const char *) "    vB.Cv   ",
           /* line */ (const char *) "    vC.Bv   ",
           /* line */ (const char *) "    vB.Cv   ",
           /* line */ (const char *) "    vC.Bv   ",
           /* line */ (const char *) "    vB.Cv   ",
           /* line */ (const char *) "    vv.vv   ",
           /* line */ (const char *) "      ^     ",
           /* end */ nullptr);
}
